import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { resolve } from "node:path";
import type { ChecklistItem } from "@pseolint/core";
import { applyManifest, type ApplyCliOptions } from "./apply.js";

const RESET = "\x1b[0m";
const DIM = "\x1b[2m";
const RED = "\x1b[31m";
const GREEN = "\x1b[32m";

const execFileP = promisify(execFile);

export interface ApplyPrOptions extends ApplyCliOptions {
  token?: string;
  /** `owner/repo`. Derived from `git remote get-url origin` when omitted. */
  repoSlug?: string;
  /** PR base branch. Derived from `origin/HEAD` when omitted, else `main`. */
  base?: string;
  /** Head branch. Default `pseolint/fix-<slug>`. */
  branch?: string;
  /** GitHub API base; override for GHE. Default `https://api.github.com`. */
  apiBase?: string;
}

/** Seams so the orchestration is testable without a real repo or network. */
export interface PrDeps {
  git: (args: string[], cwd: string) => Promise<string>;
  api: (method: string, url: string, token: string, body?: unknown) => Promise<{ status: number; json: any }>;
}

const realGit: PrDeps["git"] = async (args, cwd) => {
  const { stdout } = await execFileP("git", args, { cwd, maxBuffer: 8 * 1024 * 1024 });
  return stdout.trim();
};

const realApi: PrDeps["api"] = async (method, url, token, body) => {
  const res = await fetch(url, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      accept: "application/vnd.github+json",
      "content-type": "application/json",
      "user-agent": "pseolint",
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  return { status: res.status, json: await res.json().catch(() => ({})) };
};

// ── pure helpers (the parsing/rendering logic, the parts worth a test) ──────

/** `https://Foo.com/` → `foo-com`; used for the fix branch name. */
export function slugifyDomain(domain: string): string {
  return domain
    .replace(/^https?:\/\//, "")
    .replace(/\/.*$/, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** Parse `owner/repo` out of an ssh or https git remote URL. */
export function parseRepoSlug(remoteUrl: string): string | null {
  // git@github.com:owner/repo(.git)  |  https://github.com/owner/repo(.git)
  const m = remoteUrl.trim().match(/[:/]([^/:]+)\/([^/]+?)(?:\.git)?\/?$/);
  return m ? `${m[1]}/${m[2]}` : null;
}

/** Markdown PR body: what got auto-applied + a task list of what a human still owns. */
export function renderPrBody(domain: string, applied: number, changedFiles: string[], checklist: ChecklistItem[]): string {
  const lines: string[] = [];
  lines.push(`Automated pSEO fixes for **${domain}**, generated by \`pseolint apply\`.`);
  lines.push("");
  lines.push(`**${applied} deterministic edit${applied === 1 ? "" : "s"}** applied across ${changedFiles.length} file${changedFiles.length === 1 ? "" : "s"}:`);
  for (const f of changedFiles) lines.push(`- \`${f}\``);
  if (checklist.length) {
    lines.push("");
    lines.push(`### Needs a human (${checklist.length})`);
    lines.push("Generative or unmapped patches; pSEO Lint won't auto-write these:");
    lines.push("");
    for (const c of checklist) {
      const where = c.path ? ` (\`${c.path}\`)` : c.url ? ` (${c.url})` : "";
      lines.push(`- [ ] **${c.kind}**: ${c.title}${where}`);
    }
  }
  lines.push("");
  lines.push("<sub>🤖 opened by pSEO Lint. Review before merging; re-running updates this branch.</sub>");
  return lines.join("\n");
}

// ── orchestration ───────────────────────────────────────────────────────────

/**
 * `pseolint apply <manifest> --pr`: apply the deterministic edits, commit them
 * to a tool-owned branch, push, and open (or update) a PR whose body lists what
 * a human still has to do. Git via child_process, GitHub via a single fetch:
 * no octokit dependency in the MIT CLI.
 */
export async function runApplyPrCommand(opts: ApplyPrOptions, deps: PrDeps = { git: realGit, api: realApi }): Promise<number> {
  const strip = opts.noColor ?? !process.stdout.isTTY;
  const out = process.stdout;
  const paint = (s: string, c: string) => (strip ? s : `${c}${s}${RESET}`);
  const fail = (msg: string) => {
    out.write(paint(`✗ ${msg}\n`, RED));
    return 1;
  };

  const repoRoot = resolve(opts.repo);
  const { git, api } = deps;

  // Guardrail: refuse if there are uncommitted changes to *tracked* files; those
  // could get swept into our commit. Untracked files (the manifest itself, build
  // output) are ignored: we only `git add` the specific files we edit, so they
  // can't leak into the PR. Without -uno this refused on an untracked manifest.json,
  // breaking the documented `orchestrate --manifest-out … && apply … --pr` flow.
  let status: string;
  try {
    status = await git(["status", "--porcelain", "--untracked-files=no"], repoRoot);
  } catch (e) {
    return fail(`not a git repo (or git unavailable): ${(e as Error).message}`);
  }
  if (status.length > 0) {
    return fail(`tracked files have uncommitted changes; commit or stash first, then re-run --pr:\n${status}`);
  }

  // Apply the edits.
  const result = await applyManifest(opts);
  if (!result.ok) {
    out.write(paint(`✗ ${result.error}\n`, RED));
    if (result.hint) out.write(paint(`  ${result.hint}\n`, DIM));
    return 1;
  }
  if (result.changedFiles.length === 0) {
    out.write(paint("Nothing to fix: no deterministic edits applied. Not opening a PR.\n", DIM));
    if (result.checklist.length) out.write(paint(`(${result.checklist.length} item(s) still need a human; run without --pr to see the checklist.)\n`, DIM));
    return 0;
  }

  const token = opts.token ?? process.env.GITHUB_TOKEN;
  if (!token) return fail("no token; pass --token or set GITHUB_TOKEN.");

  let repoSlug = opts.repoSlug;
  if (!repoSlug) {
    const remote = await git(["remote", "get-url", "origin"], repoRoot).catch(() => "");
    repoSlug = parseRepoSlug(remote) ?? undefined;
    if (!repoSlug) return fail(`cannot derive owner/repo from origin remote; pass --repo-slug owner/repo.`);
  }
  const [owner, repo] = repoSlug.split("/");

  let base = opts.base;
  if (!base) {
    const head = await git(["rev-parse", "--abbrev-ref", "origin/HEAD"], repoRoot).catch(() => "");
    base = head.replace(/^origin\//, "") || "main";
  }

  const branch = opts.branch ?? `pseolint/fix-${slugifyDomain(result.domain)}`;
  const apiBase = opts.apiBase ?? "https://api.github.com";

  // Commit onto the tool-owned branch and push (force-with-lease: safe on our branch only).
  try {
    await git(["checkout", "-B", branch], repoRoot);
    await git(["add", "--", ...result.changedFiles], repoRoot);
    await git(["commit", "-m", `pseolint: fix ${result.domain}`], repoRoot);
    await git(["push", "--force-with-lease", "-u", "origin", branch], repoRoot);
  } catch (e) {
    return fail(`git push failed: ${(e as Error).message}`);
  }

  // Open or update the PR.
  const title = `pSEO Lint: fixes for ${result.domain}`;
  const body = renderPrBody(result.domain, result.applied, result.changedFiles, result.checklist);

  const existing = await api("GET", `${apiBase}/repos/${owner}/${repo}/pulls?head=${owner}:${branch}&state=open`, token);
  const openPr = Array.isArray(existing.json) ? existing.json[0] : undefined;

  let prUrl: string;
  let verb: string;
  if (openPr) {
    const upd = await api("PATCH", `${apiBase}/repos/${owner}/${repo}/pulls/${openPr.number}`, token, { title, body });
    if (upd.status >= 300) return fail(`updating PR failed (${upd.status}): ${upd.json?.message ?? ""}`);
    prUrl = upd.json.html_url;
    verb = "updated";
  } else {
    const cre = await api("POST", `${apiBase}/repos/${owner}/${repo}/pulls`, token, { title, body, head: branch, base });
    if (cre.status >= 300) return fail(`creating PR failed (${cre.status}): ${cre.json?.message ?? ""}`);
    prUrl = cre.json.html_url;
    verb = "opened";
  }

  out.write(paint(`✓ ${verb} PR: ${prUrl}\n`, GREEN));
  out.write(paint(`  ${result.applied} edit(s) on ${branch}; ${result.checklist.length} item(s) in the PR body for a human.\n`, DIM));
  return 0;
}
