import * as core from "@actions/core";
import * as github from "@actions/github";
import { auditSource } from "@pseolint/core";
import type { AuditSummary, Severity } from "@pseolint/core";

const COMMENT_MARKER = "<!-- pseolint-report -->";
const SEVERITY_ORDER: Severity[] = ["critical", "error", "warning", "info"];

function scoreLabel(score: number): string {
  if (score <= 20) return "Safe";
  if (score <= 40) return "Caution";
  if (score <= 60) return "Risky";
  if (score <= 80) return "Dangerous";
  return "Critical";
}

function formatPrComment(summary: AuditSummary): string {
  const lines: string[] = [COMMENT_MARKER];

  lines.push(`## pSEO Lint — Score: ${summary.score}/100 (${scoreLabel(summary.score)})`);
  lines.push("");
  lines.push(`**Pages analysed:** ${summary.pageCount}`);
  lines.push("");

  lines.push("| Category | Score |");
  lines.push("|----------|------:|");
  for (const [name, value] of Object.entries(summary.categoryScores)) {
    const label = name.charAt(0).toUpperCase() + name.slice(1);
    lines.push(`| ${label} | ${value} |`);
  }
  lines.push("");

  const grouped = new Map<Severity, typeof summary.findings>();
  for (const sev of SEVERITY_ORDER) {
    grouped.set(sev, []);
  }
  for (const f of summary.findings) {
    grouped.get(f.severity)!.push(f);
  }

  for (const sev of SEVERITY_ORDER) {
    const items = grouped.get(sev)!;
    if (items.length === 0) continue;

    const sevLabel = sev.charAt(0).toUpperCase() + sev.slice(1);
    lines.push(`### ${sevLabel} (${items.length})`);

    const showAll = sev === "critical" || sev === "error";
    const limit = showAll ? items.length : 5;
    const visible = items.slice(0, limit);

    for (const item of visible) {
      lines.push(`- **${item.ruleId}**: ${item.message}`);
    }

    if (!showAll && items.length > limit) {
      lines.push(`- *...${items.length - limit} more*`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push('<sub>Generated by <a href="https://pseolint.dev">pSEO Lint</a></sub>');

  return lines.join("\n");
}

async function run(): Promise<void> {
  const source = core.getInput("source", { required: true });
  const threshold = Number(core.getInput("threshold") || "40");
  const token = core.getInput("token") || process.env.GITHUB_TOKEN || "";

  core.info(`Running pseolint on ${source} with threshold ${threshold}`);

  const summary = await auditSource(source);

  core.info(`Score: ${summary.score}/100 (${summary.pageCount} pages)`);
  core.setOutput("score", summary.score);
  core.setOutput("pageCount", summary.pageCount);

  const context = github.context;
  if (token && context.payload.pull_request) {
    const octokit = github.getOctokit(token);
    const prNumber = context.payload.pull_request.number;
    const body = formatPrComment(summary);

    const { data: comments } = await octokit.rest.issues.listComments({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: prNumber,
    });

    const existing = comments.find((c) => c.body?.includes(COMMENT_MARKER));

    if (existing) {
      await octokit.rest.issues.updateComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        comment_id: existing.id,
        body,
      });
      core.info(`Updated existing PR comment #${existing.id}`);
    } else {
      await octokit.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: prNumber,
        body,
      });
      core.info("Created new PR comment");
    }
  }

  if (summary.score >= threshold) {
    core.setFailed(
      `SpamBrain Risk Score ${summary.score} exceeds threshold ${threshold}`
    );
  }
}

run().catch((err) => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
