import * as core from "@actions/core";
import * as github from "@actions/github";
import { auditSource } from "@pseolint/core";
import type { AuditSummary, RuleResult, Severity } from "@pseolint/core";

const COMMENT_MARKER = "<!-- pseolint-report -->";
const SEVERITY_ORDER: Severity[] = ["critical", "error", "warning", "info"];

function verdictLabel(verdict: AuditSummary["verdict"]): string {
  switch (verdict) {
    case "ready":      return "Ready";
    case "caution":    return "Caution";
    case "concerning": return "Concerning";
    case "critical":   return "Critical";
  }
}

function flattenIssues(summary: AuditSummary): RuleResult[] {
  return [
    ...summary.issues.blockers,
    ...summary.issues.shouldFix,
    ...summary.issues.informational,
  ];
}

function formatPrComment(summary: AuditSummary): string {
  const lines: string[] = [COMMENT_MARKER];
  const allFindings = flattenIssues(summary);

  lines.push(`## pseolint — Verdict: ${verdictLabel(summary.verdict)} (risk ${summary.risk}/100, lower is better)`);
  lines.push("");
  lines.push(`**Pages analysed:** ${summary.pageCount}`);
  if (summary.templateDetected) {
    lines.push("");
    lines.push("> Template-generated content detected. Fix suggestions are tailored for template authors.");
  }
  if (summary.siteClassification) {
    lines.push("");
    lines.push(`> Site type: \`${summary.siteClassification.type}\` (${Math.round(summary.siteClassification.confidence * 100)}% confidence). ${summary.siteClassification.suppressedRules.length} pSEO-only rule${summary.siteClassification.suppressedRules.length === 1 ? "" : "s"} suppressed.`);
  }
  lines.push("");

  lines.push("| Category | Grade | Issues |");
  lines.push("|----------|:-----:|------:|");
  for (const [name, info] of Object.entries(summary.categories)) {
    const label = name.charAt(0).toUpperCase() + name.slice(1);
    lines.push(`| ${label} | ${info.grade} | ${info.issues} |`);
  }
  lines.push("");

  const grouped = new Map<Severity, RuleResult[]>();
  for (const sev of SEVERITY_ORDER) {
    grouped.set(sev, []);
  }
  for (const f of allFindings) {
    grouped.get(f.severity)!.push(f);
  }

  for (const sev of SEVERITY_ORDER) {
    const items = grouped.get(sev)!;
    if (items.length === 0) continue;

    const sevLabel = sev.charAt(0).toUpperCase() + sev.slice(1);
    lines.push(`### ${sevLabel} (${items.length})`);

    const showAll = sev === "critical" || sev === "error";
    const limit = showAll ? items.length : 5;
    const visible = items.slice(0, limit);

    for (const item of visible) {
      const effortStr = item.effort ? ` (**${item.effort}**)` : "";
      lines.push(`- **${item.ruleId}**${effortStr}: ${item.message}`);
    }

    if (!showAll && items.length > limit) {
      lines.push(`- *...${items.length - limit} more*`);
    }

    lines.push("");
  }

  lines.push("---");
  lines.push('<sub>Generated by <a href="https://pseolint.dev">pSEO Lint</a></sub>');

  return lines.join("\n");
}

async function run(): Promise<void> {
  const source = core.getInput("source", { required: true });
  const threshold = Number(core.getInput("threshold") || "40");
  const token = core.getInput("token") || process.env.GITHUB_TOKEN || "";

  core.info(`Running pseolint on ${source} with risk threshold ${threshold}`);

  const summary = await auditSource(source);

  core.info(`Verdict: ${verdictLabel(summary.verdict)} · risk ${summary.risk}/100 (${summary.pageCount} pages)`);
  // Outputs preserved for backwards compatibility with downstream workflow steps
  // that read `score` — the value now reflects `risk` (numerically identical).
  core.setOutput("score", summary.risk);
  core.setOutput("risk", summary.risk);
  core.setOutput("verdict", summary.verdict);
  core.setOutput("pageCount", summary.pageCount);

  const context = github.context;
  if (token && context.payload.pull_request) {
    const octokit = github.getOctokit(token);
    const prNumber = context.payload.pull_request.number;
    const body = formatPrComment(summary);

    const { data: comments } = await octokit.rest.issues.listComments({
      owner: context.repo.owner,
      repo: context.repo.repo,
      issue_number: prNumber,
    });

    const existing = comments.find((c) => c.body?.includes(COMMENT_MARKER));

    if (existing) {
      await octokit.rest.issues.updateComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        comment_id: existing.id,
        body,
      });
      core.info(`Updated existing PR comment #${existing.id}`);
    } else {
      await octokit.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: prNumber,
        body,
      });
      core.info("Created new PR comment");
    }
  }

  if (summary.risk >= threshold) {
    core.setFailed(
      `pseolint risk ${summary.risk} exceeds threshold ${threshold} (verdict: ${verdictLabel(summary.verdict)})`
    );
  }
}

run().catch((err) => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
