// AUTO-GENERATED by scripts/gen-okf.ts from apps/web MARKETING_RULES: do not edit.
// Regenerate with `bun run gen:okf`. Lean, actionable subset for MCP resources.
export interface RuleKnowledge {
  ruleId: string;
  slug: string;
  category: string;
  title: string;
  oneLiner: string;
  whatItDetects: string;
  howToFix: string[];
  url: string;
}

export const RULE_KNOWLEDGE: RuleKnowledge[] = [
  {
    "ruleId": "spam/thin-content",
    "slug": "thin-content",
    "category": "spam",
    "title": "Thin Content Detection, How Google Catches Low-Substance Pages",
    "oneLiner": "Google's Helpful Content System (rebuilt August 25, 2022) demoted an estimated 45% of low-effort pages in the March 5, 2024 scaled-content-abuse update, the spam/thin-content rule mirrors that floor by flagging every URL under 300 words of substantive body text (default), after stripping nav and footer chrome via SpamBrain-style readability heuristics.",
    "whatItDetects": "300 words is the default floor pseolint flags pages against, the threshold Google's SpamBrain classifier has been tuned to since the March 5, 2024 scaled-content-abuse update (https://developers.google.com/search/docs/essentials/spam-policies). The rule extracts the page's main content text (after stripping nav, footer, and other chrome) splits on whitespace, and counts non-empty tokens. Any URL whose word count is below the threshold you pass to the rule (defaults differ per pSEO archetype: 200 for product comparators, 350 for guide-style hubs) is added to a `thinContentUrls` set and reported with the exact deficit. That set is then reused by other rules (most notably `spam/doorway-pattern`) so a thin page that also looks templated escalates from a single error (weight 25) to a critical signal stack (weight 40). The check is intentionally cheap and deterministic; it does not try to evaluate quality, only volume of substantive prose.",
    "howToFix": [
      "Audit URL-by-URL, not in aggregate. A 50%-thin domain usually has clusters of completely empty pages; collapsing those is faster than rewriting everything.",
      "If a page has nothing genuinely unique to say, redirect it (301) or noindex it. Pruning is a feature, not a failure.",
      "Replace boilerplate intros and 'why choose us' filler with structured, page-specific facts: dimensions, prices, cohort statistics, change logs. Facts add words and quality at the same time.",
      "Connect a real data source (CSV, JSON, or your DB) so each entity contributes its own attributes. Pages should diverge on the facts, not just the H1.",
      "Raise your `thinMinWords` threshold gradually as you fix pages. Catching the next batch is easier when the floor moves up.",
      "Do not pad with FAQ accordions copied across the site; that triggers `spam/boilerplate-ratio` instead and you end up worse off."
    ],
    "url": "https://pseolint.dev/rules/thin-content"
  },
  {
    "ruleId": "spam/doorway-pattern",
    "slug": "doorway-pattern",
    "category": "spam",
    "title": "Doorway Pages, How Google Detects Templated Funnels",
    "oneLiner": "Google has banned doorway pages since the March 16, 2015 Search Central post, pseolint's spam/doorway-pattern rule mirrors SpamBrain's convergence logic by requiring 3 independent signals to stack (SimHash near-duplicate above 0.85, entity-swap, and structural confirmation) before firing at error severity (weight 25), the highest-confidence spam pattern reported by @pseolint/core v0.4.3.",
    "whatItDetects": "3 independent signals must converge before pseolint fires this rule, mirroring the convergence logic Google's SpamBrain has used to enforce the doorway-pages policy (https://developers.google.com/search/docs/essentials/spam-policies#doorway-pages) since March 16, 2015. The rule does not run a single check. It joins the output of two earlier rules, `spam/near-duplicate` (64-bit SimHash similarity above the 0.85 default threshold) and the entity-swap detector (pages whose only meaningful diff is a swapped noun phrase), then layers on additional confirmations: identical `structureSignature`, identical `<meta description>`, and whether either URL is already in the thin-content set (300-word default floor). A pair only triggers `spam/doorway-pattern` once at least 3 of these signals agree. The finding fires at error severity (weight 25 in pseolint's scoring, against critical=40, warning=12, info=5) and names both URLs alongside which signals stacked, so you can see at a glance whether you are looking at a near-duplicate problem (fix the content) or a template problem (fix the layout).",
    "howToFix": [
      "Identify which signal you can break most cheaply. Usually it is the meta description: write per-page descriptions before touching content.",
      "Differentiate the structure: introduce conditional sections that only render for pages with certain attributes (e.g., a 'Free tier' callout that only appears for free competitors).",
      "If two pages serve the same intent, merge them. A single 1,500-word /alternatives/ page often outranks ten thin /vs/ pages.",
      "Inspect the entity-swap pairs first; that is the rule's strongest signal and where the worst offenders cluster.",
      "Once you fix a pair, re-run pseolint. Doorway findings drop noisily: fixing one pair often resolves five because of how SimHash buckets cluster.",
      "Do not try to defeat the rule by injecting boilerplate variation (random sentences, swapped synonyms). SpamBrain has the same defenses; you will fail both."
    ],
    "url": "https://pseolint.dev/rules/doorway-pattern"
  },
  {
    "ruleId": "spam/near-duplicate",
    "slug": "near-duplicate",
    "category": "spam",
    "title": "Near-Duplicate Pages, SimHash, SpamBrain, and the Similarity Threshold",
    "oneLiner": "85% SimHash similarity is the pseolint default threshold, every page pair at or above that mirrors the near-duplicate canonicalisation ceiling Google's web indexing team has used since adopting Charikar's 2002 SimHash paper in 2007, and which the March 5, 2024 scaled-content-abuse update reaffirmed as policy via SpamBrain's 60-second triage queue.",
    "whatItDetects": "85% SimHash similarity is the threshold pseolint flags page pairs at, mirroring the near-duplicate canonicalisation ceiling Google's web indexing team has used since adopting Charikar's 2002 SimHash paper in 2007, and named again in the March 5, 2024 scaled-content-abuse policy (https://developers.google.com/search/docs/essentials/spam-policies). For each page, the rule computes a 64-bit SimHash from the main content text using token-level shingling, chosen over Jaccard (too slow at O(n*m)) and BERT embeddings (too expensive for a 60-second audit budget). It then compares every page against every other page, an O(n²) sweep that is fine for the page counts pSEO sites actually run (the 200-page free-tier audit ceiling completes in under a 1-second wall-clock; the 500-page Pro manual-re-audit ceiling stays within the 30-second per-rule budget).\n\nHamming distance between two hashes is converted to a similarity score in [0,1]. Any pair scoring at or above the configured threshold (default 85%, escalated to 90% for template-heavy sites) is recorded both as a finding and as a `PairMatch` consumed by `spam/doorway-pattern`. The finding fires at warning severity (weight 12) and includes the exact similarity percentage so you can sort the queue worst-first. Implementation lives in @pseolint/core v0.7.0 (current), MIT-licensed at github.com/ouranos-labs/pseolint, and runs in the same pipeline industry crawlers Ahrefs, Sitebulb, and Screaming Frog use for their dedup counters.",
    "howToFix": [
      "Sort findings by similarity percentage descending; fix pairs above 0.95 first; those are almost always copy-paste accidents you can resolve in minutes.",
      "For pairs in the 0.85-0.95 range, decide whether the duplication is intentional (merge into one page with a 301) or accidental (rewrite one to genuinely differentiate).",
      "Add canonicals only as a last resort; they preserve the duplicate URL in the index, which still drags on cluster authority.",
      "Re-run with a stricter threshold (0.80) once you've cleared the worst tier. The tail of medium-similarity pairs often hides templating problems that `spam/boilerplate-ratio` will then surface.",
      "Audit your data source: many near-duplicate clusters trace back to two source rows that should have been one (e.g., 'San Francisco' and 'SF, California' as separate entities)."
    ],
    "url": "https://pseolint.dev/rules/near-duplicate"
  },
  {
    "ruleId": "spam/boilerplate-ratio",
    "slug": "boilerplate-ratio",
    "category": "spam",
    "title": "Boilerplate Ratio, When Shared Template Text Eats Your Pages",
    "oneLiner": "60% is the default boilerplateMaxRatio: pseolint identifies sentence-level blocks appearing on 80%+ of pages, then flags any URL whose word count is dominated by those repeated blocks (warning severity, weight 12).",
    "whatItDetects": "pseolint flags pages whose boilerplate ratio exceeds 60%, the threshold operationalising the 'producing many pages on the same topic to such a degree that individual pages have very little unique value' clause Google added to the helpful-content guidance in the March 5, 2024 scaled-content-abuse update (https://developers.google.com/search/docs/essentials/spam-policies). The rule splits each page's content into sentence-sized blocks (split on `.!?\\n`, lower-cased, blocks shorter than 20 characters discarded). It builds a frequency map across all pages, then defines the 'skeleton' as any block appearing on at least 80% of pages plus one. For each individual page, it sums the words inside skeleton blocks and divides by the page's total word count. Pages above your `boilerplateMaxRatio` (default 0.60) are reported with the exact percentage. Crucially, the skeleton is computed across the actual pages you crawled, so if you sample only 20 pages of a 2,000-page site, the skeleton may be smaller than reality and the ratio is conservatively low.",
    "howToFix": [
      "Find your skeleton blocks first. Run pseolint with `--verbose` and the rule will list which exact sentences it considers boilerplate; that's your edit list.",
      "Move repeated content out of the page body and into the global footer or a separate /about-style URL where it doesn't count against per-page ratio.",
      "Shorten or delete sections that aren't load-bearing. 'Why this works' intros and pre-conclusion summaries are the highest-value cuts because they are uniformly low information.",
      "Grow the variable section. The ratio is a fraction; a smaller numerator is one path, a larger denominator is another. Adding genuine per-page facts is almost always safer than aggressive boilerplate removal.",
      "Treat anything above 50% as a yellow flag even if it passes the rule. The default 60% threshold is permissive; many domains that pass at 0.60 still feel templated to a reader.",
      "Re-run after each round of edits. Removing one skeleton block can shift others' frequencies above the 80% cutoff, so the skeleton recomposes."
    ],
    "url": "https://pseolint.dev/rules/boilerplate-ratio"
  },
  {
    "ruleId": "spam/template-diversity",
    "slug": "template-diversity",
    "category": "spam",
    "title": "Template Diversity, Why HTML Structure Counts as a Spam Signal",
    "oneLiner": "30% is the default minUniqueRatio threshold, pseolint warns when fewer than 30% of pages carry a structurally distinct HTML skeleton, the floor at which SpamBrain (rebuilt August 25, 2022) starts reading a domain as one template rather than N designed pages.",
    "whatItDetects": "30% is the default minUniqueRatio pseolint warns below, the floor at which Google's SpamBrain (rebuilt August 25, 2022 alongside the Helpful Content System launch to score site-level helpfulness alongside per-page signals) starts treating a domain as a single template rather than N designed pages. Each parsed page carries a `structureSignature`, a hash of its HTML structure that ignores text content but preserves the sequence and nesting of element types. The rule counts how many distinct signatures exist across all pages and divides by the page count to produce a unique-ratio in [0,1]. If that ratio falls below `minUniqueRatio` (0.30 default), a single warning-severity finding (weight 12) is emitted at the site level, versus error=25, critical=40, info=5 elsewhere in the engine. This is a holistic signal, not a per-page one: there is no list of 'failing' URLs because the problem is the site's design system, not any individual page. Powered by @pseolint/core v0.7.0, MIT-licensed at github.com/ouranos-labs/pseolint.",
    "howToFix": [
      "Identify which sections in your template should be optional. Anything that doesn't apply to every entity is a candidate: pricing tables, video embeds, timelines, FAQs, comparison widgets.",
      "Wrap optional sections in conditionals that key off the underlying data, not random booleans. 'If the entity has a video URL, render the video block' produces meaningful diversity; 'if Math.random() > 0.5' produces nothing.",
      "Vary the order of secondary sections by entity type. A restaurant page might lead with menu, a hotel page with rooms: same template, different priority.",
      "Add per-entity media variations. Some pages have hero images, some have hero videos, some have galleries. Each renders different HTML.",
      "Don't fix this rule by adding random structural noise. The rule is a holistic warning; if the underlying content is differentiated, the warning is acceptable on a homogeneous content type."
    ],
    "url": "https://pseolint.dev/rules/template-diversity"
  },
  {
    "ruleId": "links/host-section-divergence",
    "slug": "host-section-divergence",
    "category": "links",
    "title": "Site Reputation Abuse, Detecting Parasite Sections on a Trusted Host",
    "oneLiner": "Google's May 7, 2024 site-reputation-abuse policy demotes subfolders that borrow a host's reputation without earning it, links/host-section-divergence flags a URL section (e.g. /coupons/, /deals/) only when it diverges from the rest of the host on at least 2 of 4 independent structural signals, and it deliberately fires on the minority section, never on a balanced multi-topic split.",
    "whatItDetects": "The rule groups every crawled URL by its first path segment (/coupons/, /reviews/, /best/) and tests each section that holds at least 10 pages while leaving at least 10 pages in the rest of the host. It only considers sections that are a strict minority of the corpus (under 50%), reputation abuse is, by definition, a small parasite section riding a larger host, so a 50/50 split is read as a multi-topic site and skipped.\n\nFor each qualifying section it measures four signals against the rest of the host: (1) inbound-link integration, the fraction of section pages that receive at least one internal link from outside the section, flagged when under 0.20 (the section is an island the host barely references); (2) topic divergence, Jaccard distance between the top-100 TF-IDF terms of the section versus the rest, flagged above 0.75 (under ~25% vocabulary overlap); (3) template isolation, the fraction of section pages whose structureSignature also appears anywhere else on the host, flagged when under 0.10 (the section ships its own template the host never uses); and (4) authorship mismatch, flagged when section and host byline coverage differ by at least 0.40 and one pool is mostly anonymous (≤0.30) while the other is mostly bylined (≥0.70).\n\nA section that trips 2 or more signals emits a warning naming the section, the signal values, and a 20-URL sample; a section that trips 3 or more and holds over 50 pages escalates to error. The rule reasons about structure, not contracts; it cannot read a revenue-share agreement or see a manual action, only the structural fingerprint those arrangements leave behind.",
    "howToFix": [
      "Decide per section whether you actually own it editorially. If a third party produces the content with minimal first-party review, the honest fixes are to integrate it properly or to move it off the host: not to game the four signals.",
      "Integrate, option A: cross-link the section from your primary navigation and from topically-related host pages so it stops reading as an island. Low inbound integration is the cheapest signal to flip and often the most diagnostic.",
      "Integrate, option B: share authorship and schema. Put real, named reviewers on the pages who actually vet them, and align the section's template with the rest of the host so it isn't a structurally foreign body.",
      "Separate, the clean alternative: move the section to a subdomain or a partner-owned domain and 301 the old URLs. It stops borrowing your reputation (which is the point of the enforcement) and stops being a liability.",
      "Do not try to defeat the rule by sprinkling a few host links into the section while leaving it editorially third-party. The policy is about substance, not surface signals; a reviewer applies the same 'would a reasonable user see this as the host's own content' test the rule only approximates."
    ],
    "url": "https://pseolint.dev/rules/host-section-divergence"
  },
  {
    "ruleId": "spam/entity-swap",
    "slug": "entity-swap",
    "category": "spam",
    "title": "Entity-Swap Pages, When Only the Noun Changes Between URLs",
    "oneLiner": "spam/entity-swap masks the variable noun on every page (by default US state names and 5-digit ZIP codes) then computes a 64-bit SimHash of what is left and fires at critical severity when two pages score 95% similarity or higher, the convergence signal Google's SpamBrain has used against entity-swap doorways since the March 5, 2024 scaled-content-abuse update.",
    "whatItDetects": "spam/entity-swap is the rule that catches the single cleanest fingerprint of programmatic generation: a page whose only real difference from its siblings is the entity you swapped in. The rule masks every page's main content with your entity patterns, the defaults cover all 50 US state names and 5-digit ZIP codes, and you add your own dimensions (cities, SKUs, job titles) in pseolint.config.ts, and then computes a 64-bit SimHash over the masked text.\n\nMasking is what separates this rule from spam/near-duplicate. Near-duplicate hashes the raw text and fires at 85%, so two location pages with genuinely different city paragraphs can slip under its bar. Entity-swap removes the entity tokens first, so if the remaining sentence frames are identical the masked similarity rockets toward 100%. The pairwise O(n²) sweep flags any pair scoring 95% or above at critical severity, and records the pair as a PairMatch that spam/doorway-pattern later consumes as one of the three signals it needs to converge.",
    "howToFix": [
      "Bind real per-entity data, not synonyms. Swapping 'top' for 'best' or rewording a sentence leaves the masked SimHash untouched; the rule already ignores the entity token, so only genuinely different facts move the score.",
      "Lead each page with the one thing that entity has and its siblings lack (a local statute, a region-specific fee, a SKU's actual spec) so the opening sentence frame diverges, not just the noun.",
      "Audit your data source for thin records. An entity-swap cluster usually traces back to rows that carry no distinguishing fields; if the data cannot differentiate the page, the page probably should not exist as a separate URL.",
      "Consolidate entities you cannot differentiate. Five states with identical programs are better served by one page that names all five than five pages that pretend to be different.",
      "Re-run after each fix. Because the rule is pairwise, breaking one page out of a cluster can drop several findings at once as the remaining pairs fall below 95%."
    ],
    "url": "https://pseolint.dev/rules/entity-swap"
  },
  {
    "ruleId": "spam/publication-velocity",
    "slug": "publication-velocity",
    "category": "spam",
    "title": "Publication Velocity, When Your Publish Dates Betray Bulk Generation",
    "oneLiner": "spam/publication-velocity groups your pages by publish date and warns when any single day exceeds the greater of 100 pages or 10% of your whole corpus, the date-stacking signal Google's March 27, 2026 core update tightened against programmatically generated sites.",
    "whatItDetects": "spam/publication-velocity reads the publish date off every page (from article:published_time, a datePublished meta, or the first time[datetime] element) truncates it to a calendar day, and groups the corpus by that day. Pages with no detectable date are skipped, so the rule only judges what it can actually see.\n\nThe ceiling is corpus-relative. The effective limit for any day is the greater of two numbers: the absolute floor of 100 pages per day, and 10% of your total page count. A 400-page site is governed by the 100/day floor; a 50,000-page site can legitimately publish up to 5,000 pages on one date before the rule says anything. Any day that exceeds its effective limit emits a single warning naming the date, the count, and which ceiling it breached. The corpus-relative design is what keeps the rule from punishing large, legitimately busy publishers while still catching the small site that stamped 800 generated pages with one timestamp.",
    "howToFix": [
      "Spread real dates, do not fabricate them. If your pages were genuinely created over time, surface that true history in article:published_time instead of stamping every record with the import date.",
      "Drip-publish new batches. Releasing generated pages over days or weeks both lowers the per-day count and matches how Google expects a healthy site to grow.",
      "Raise the corpus, not the spike. The ceiling scales with total page count, so the rule naturally relaxes as a site earns scale, but only if growth is distributed, not stacked.",
      "Check which field you expose. If you have no real publish dates, consider omitting them rather than stamping a placeholder, since the rule skips pages with no detectable date.",
      "Treat a velocity warning as a prompt to audit the same template for thin-content and near-duplicate: date-stacking rarely travels alone."
    ],
    "url": "https://pseolint.dev/rules/publication-velocity"
  },
  {
    "ruleId": "spam/template-coverage",
    "slug": "template-coverage",
    "category": "spam",
    "title": "Template Coverage, How Sparse Keyword Matrices Expose pSEO",
    "oneLiner": "spam/template-coverage groups URLs in the same directory, masks the entity tokens in each filename, and reports how many of the possible dimension combinations a template actually fills, surfacing, at info severity, the sparse high-dimension matrices Google's March 27, 2026 core update down-weighted on programmatic sites.",
    "whatItDetects": "spam/template-coverage is a diagnostic, not an accusation. It groups your URLs into clusters by parent directory, and within each cluster of at least 5 pages it looks only at the filename, the last path segment, extension stripped. It masks the entity tokens in that filename using your entity patterns, then splits the masked name on hyphens into positional tokens.\n\nFor each position where more than one distinct value appears, the rule records a 'dimension'. A cluster like /jobs/[role]-jobs-in-[city] has two dimensions: role and city. The rule multiplies the number of distinct values in each dimension to get the total possible combinations, then divides the pages you actually built by that total to produce a coverage percentage. If a template has 12 services and 50 cities (600 possible cells) but you shipped 96 pages, coverage is 16% and the rule reports the dimensions, the sample values, and the ratio at info severity. A cluster where every token varies, or none does, produces no finding because there is no matrix to measure.",
    "howToFix": [
      "Narrow the matrix to what you can differentiate. If you cannot write genuinely distinct content for all 600 cells, do not claim the grid: build the cells you can substantiate and drop the dimensions you cannot.",
      "Raise coverage by subtraction, not addition. Pruning empty intent often beats generating the missing cells, because the missing cells are usually the ones with no demand and nothing unique to say.",
      "Check the paired findings first. A coverage finding next to spam/thin-content or spam/near-duplicate in the same cluster is the combination that matters; coverage alone is a diagnostic to note, not an emergency.",
      "Collapse a dimension. If one axis (say, modifier words like cheap/best/top) adds combinations without adding user value, remove it from the URL structure and fold it into a single page.",
      "Treat info severity as guidance. The rule never blocks a verdict on its own; it tells you where a template's ambition outruns its substance so you can decide before Google does."
    ],
    "url": "https://pseolint.dev/rules/template-coverage"
  },
  {
    "ruleId": "content/unique-value",
    "slug": "unique-value",
    "category": "content",
    "title": "Unique Value, Originality as a Density, Not a Word Count",
    "oneLiner": "content/unique-value scores how original each page is as a rarity density (every distinct word weighted by how rare it is across the audit, then averaged) and fires when that density falls below the floor, the page-specific-vocabulary test Google's scaled-content-abuse policy has applied since March 5, 2024 when it asks whether a URL adds anything genuinely new.",
    "whatItDetects": "content/unique-value asks how original a page is relative to its siblings, as a density rather than a raw count. It tokenises each page's main content, lower-cased, split on whitespace, with leading and trailing punctuation stripped so 'word', 'word.' and '(word)' count as one token, and weights every distinct word by how rare it is across the audited set: a word on one page scores 1, a word on every page scores near 0 (normalised inverse document frequency). The page's score is the average of those weights, its unique-content density, between 0 and 1.\n\nA page whose vocabulary mostly repeats across its siblings (boilerplate, shared spec blocks, an entity-swapped template) scores low and fires. Because it is an average, the metric does not punish a page for being short or for living in a large, tightly-themed site, and it does not flip on a one-word margin the way a hard count does. Volume is spam/thin-content's job; exact twins are spam/near-duplicate's; this rule isolates low originality.",
    "howToFix": [
      "Write a page-specific lead. The fastest way to raise density is an opening paragraph true of this entity and nothing else. Boilerplate intros are the first thing to cut.",
      "Move shared blocks to a shared URL. A glossary, a methodology note, or a legal disclaimer that repeats across pages should live on one page the others link to, not embedded everywhere where it dilutes uniqueness.",
      "Stop expecting per-axis data to count. Content repeated across pages on the same axis (a role's regulations across that role's documents) is common vocabulary and barely moves density. Only text specific to this page raises it.",
      "Bind distinct records, not shared ones. If two pages pull the same fields from your data source, they will share vocabulary; differentiate the records or merge the pages.",
      "Read the density and overlap the finding reports. It tells you how distinctive the page is and confirms the problem is overlap, not length."
    ],
    "url": "https://pseolint.dev/rules/unique-value"
  },
  {
    "ruleId": "content/meta-uniqueness",
    "slug": "meta-uniqueness",
    "category": "content",
    "title": "Meta Description Uniqueness, When Snippets Are Templated",
    "oneLiner": "content/meta-uniqueness masks the entity tokens in every page's meta description, lower-cases and trims what remains, and fires an error the moment two or more pages collapse to the same string, the templated-snippet pattern Google has treated as scaled content since the March 5, 2024 spam update.",
    "whatItDetects": "content/meta-uniqueness checks the one piece of copy most teams forget to vary: the meta description. For every page that has one, the rule masks the entity tokens using your entity patterns, then lower-cases and trims the result. Pages whose masked descriptions are byte-for-byte identical are grouped together.\n\nAny group with two or more members fires an error naming the count of pages that share the template. The masking is the important part. A description like 'Compare {tool} against the competition, pricing, features, and migration paths' looks unique on the surface for every tool, but the moment you mask the tool name, all of them collapse to the same sentence. That collapse is the signal: the description was generated from a template, not written for the page. The rule deliberately uses exact-match-after-masking rather than fuzzy similarity, so it only fires when the underlying snippet really is one template wearing different nouns.",
    "howToFix": [
      "Bind a distinct value into every description. A per-page count, price, date, or named attribute pulled from your data source breaks the masked-match because the variable part survives masking.",
      "Do not rely on the entity alone. Swapping only the city or role is exactly what the rule masks away; the description must vary on something the mask does not remove.",
      "Write the description from the page's most specific fact. The best snippets answer 'why this page' in 155 characters: the same discipline that satisfies the rule makes the SERP result more clickable.",
      "Audit templates, not pages. One bad description template generates thousands of duplicates; fix the template's data binding once and the entire cluster clears.",
      "Check for empty descriptions too: pages with no meta description are skipped here, but they surface in tech/og-completeness and lose snippet control for a different reason."
    ],
    "url": "https://pseolint.dev/rules/meta-uniqueness"
  },
  {
    "ruleId": "content/missing-author",
    "slug": "missing-author",
    "category": "content",
    "title": "Missing Author, Why Anonymous pSEO Pages Fail E-E-A-T",
    "oneLiner": "Google added the second E for Experience to its E-A-T trust framework on December 15, 2022, and content/missing-author mirrors that shift by flagging at warning severity, medium confidence, every page that exposes none of four author signals, a meta author tag, a schema author field, a byline element, or a rel=author link.",
    "whatItDetects": "content/missing-author checks one thing per page: is there any machine-readable claim of who wrote it? The rule reads four independent author signals the parser extracts and fires only when all four are absent.\n\nThe signals are precise. (1) Meta author, a non-empty content value on a `<meta name=\"author\">` tag, after whitespace normalisation, so an empty tag does not count. (2) Schema author, any JSON-LD object on the page that carries an `author` key, which covers Article, BlogPosting, and NewsArticle structured data. (3) Byline element, at least one element whose class contains 'author' or 'byline', or which carries `rel='author'`, catching the visible '.byline' or '.author-name' markup most templates ship. (4) Rel=author link, an `<a rel=\"author\">` or `<link rel=\"author\">` anchor pointing at a profile.\n\nA page passes if even one of the four is present, so the bar is deliberately low. Severity is fixed at warning and confidence at medium, because technical docs, product pages, and pricing pages legitimately omit bylines, attribution matters most on blog and news content where authorship is the primary trust signal.",
    "howToFix": [
      "Add a `<meta name=\"author\" content=\"Full Name\">` to every content page's head; it is the single cheapest signal and clears the rule on its own.",
      "Put the author into your JSON-LD: an Article or BlogPosting node with an `author` object carrying a name and, ideally, a sameAs link to a real profile.",
      "Render a visible byline in markup the rule recognises (an element classed 'author' or 'byline', or one carrying rel='author') so humans and the parser see the same attribution.",
      "Link the byline to a genuine author bio page that documents the writer's relevant experience, not a stub; the link is what turns a name into an E-E-A-T signal.",
      "Decide which page types actually need authors. Technical docs and pricing pages can stay unsigned; blog, news, and 'guide' content should not, since that is where attribution carries the most trust weight.",
      "Audit site-wide before launch: if every page is anonymous on a site deeper than three pages, the rule emits one site-level E-E-A-T warning instead of per-URL findings, so fix the template once rather than page by page."
    ],
    "url": "https://pseolint.dev/rules/missing-author"
  },
  {
    "ruleId": "content/eeat-signals",
    "slug": "eeat-signals",
    "category": "content",
    "title": "E-E-A-T Signals, When a Page Carries No Evidence of Who Wrote It",
    "oneLiner": "content/eeat-signals checks four trust categories on every page (an about-page link, an author byline, a published date, and a sources or references marker) then fires at info severity for any URL carrying fewer than 2 of the 4, the anonymity pattern Google's E-E-A-T framework has weighed against pages since its December 2022 Quality Rater Guidelines update.",
    "whatItDetects": "content/eeat-signals scores each page against four independent trust categories and counts how many it carries. The first is an about-page link: the rule scans the page's resolved hrefs for any URL matching '/about'. The second is an author signal, satisfied if the page exposes a non-empty author meta tag, a schema.org author, a byline element, or a rel=author link. The third is a published date the parser could extract. The fourth is a 'sources' category, matched when the raw HTML contains any of five patterns: 'last updated', 'last modified', 'reviewed by', 'sources:', or 'references:'.\n\nA page passes if it carries 2 or more of those 4 categories. Any page below that floor is flagged. The rule never inspects the quality of the byline or the accuracy of the date; it only asks whether the markers of accountability are present at all. The point is structural: a page that names nobody, dates nothing, links to no about page, and cites no source is anonymous by construction, and anonymity is the baseline condition Google's trust evaluation reads first.",
    "howToFix": [
      "Add a real author byline to every template. A meta author tag, a schema.org author property, a visible byline element, or a rel=author link each satisfies the author category: pick one and bind a genuine name, not a brand placeholder.",
      "Expose a published or updated date. The rule reads the date the parser extracts, so surface a real article:published_time or a visible 'Last updated' line rather than leaving the page undated.",
      "Link to an about page from the template footer or header. Any href matching '/about' resolves the category, and one shared link covers the whole corpus at once.",
      "Cite sources where the topic warrants it. A 'Sources:' or 'References:' block, or a 'Reviewed by' line, matches the rule's patterns and gives readers and raters something to verify against.",
      "Treat a site-wide finding as a template fix, not a per-page chore. When every page is below the floor, the cause is one template missing accountability markers: add them once at the template level and the whole cluster clears.",
      "Prioritise the fix on Your-Money-or-Your-Life pages first, where Google's guidelines weigh visible expertise most heavily before granting trust."
    ],
    "url": "https://pseolint.dev/rules/eeat-signals"
  },
  {
    "ruleId": "content/title-uniqueness",
    "slug": "title-uniqueness",
    "category": "content",
    "title": "Title Uniqueness, Missing, Too-Short, and Duplicate Page Titles",
    "oneLiner": "content/title-uniqueness rolls three checks into one rule, a missing or empty title, a title outside the 10-to-70-character band, and two or more pages sharing the exact same raw title, and it raised this gap to a tier-1 fix in pseolint after the 2026-05-03 blind-spot audit because Google ranks the title above every other on-page element.",
    "whatItDetects": "content/title-uniqueness runs three checks over the title that the existing meta-description rule never touched. First, a missing title: any page whose <head><title> is absent, empty, or whitespace-only fires an error, because the title is the strongest on-page signal Google ranks against. Second, length. A title under 10 characters fires a warning, short titles get rewritten by Google from the H1 or anchor text, so the copy you wrote never shows. A title over 70 characters fires an info finding, because Google truncates the SERP snippet around 60 characters and the tail is lost.\n\nThird, exact duplicates. The rule groups every page by its raw, trimmed title string and fires an error the moment two or more pages share one. It does NOT entity-mask the way the meta rule does, 'Slack to Google Sheets' and 'Slack to Airtable' are different raw strings and stay separate, so the rule never false-positives on a legitimate templated catalog whose titles already carry the per-record entity.",
    "howToFix": [
      "Add a non-empty <head><title> to every page. If a template can render without one, that is the first leak to plug; the title is the field Google reads before any other.",
      "Bind the per-record entity into the title so duplicates cannot form. A raw string carrying the integration name, currency pair, or city is unique by construction and never groups.",
      "Keep titles inside the 10-to-70-character band. Expand anything under 10 characters so Google does not rewrite it from the H1; tighten anything over 70 so the SERP does not truncate the tail.",
      "Front-load the distinguishing words. Google truncates around 60 characters, so the entity and primary keyword belong at the start, not after a long brand suffix.",
      "Never treat an inline SVG <title> as the page title. That logo accessibility label is decorative and crawlers ignore it: add a real <head><title> with the page entity instead.",
      "Re-run the audit after editing a template. Fixing one duplicated title clears the whole group at once, since the rule reports per shared string, not per URL."
    ],
    "url": "https://pseolint.dev/rules/title-uniqueness"
  },
  {
    "ruleId": "content/heading-structure",
    "slug": "heading-structure",
    "category": "content",
    "title": "Heading Structure, Missing, Duplicate, and Unstructured Headings",
    "oneLiner": "content/heading-structure runs three checks on every page Google crawls, a missing H1 fires an error because it is almost always a CMS or template bug, two or more H1 elements raise a warning that the HTML5 outline and accessibility checkers both dislike, and any page past 600 words with no H2 sub-structure emits an info note about Featured Snippet eligibility.",
    "whatItDetects": "content/heading-structure runs three independent checks over every parsed page and emits one finding per problem it sees. First, if a page has zero <h1> elements it fires an error, a page with no top-level heading is almost always a CMS misconfiguration or a template that forgot to render the title, and Google leans on the H1 to disambiguate the page's primary topic when the title tag is weak.\n\nSecond, if a page carries more than one <h1>, the rule raises a warning and reports the count. A single H1 per document is the convention every accessibility checker enforces and several SEO heuristics still expect, so multiple H1s read as an ambiguous primary-topic signal.\n\nThird, the rule measures the page's body word count by splitting the main text on whitespace; once that count reaches 600 words and the page has no <h2> at all, it emits an info finding. A long wall of text with no sub-headings is a readability and Featured Snippet problem, not a correctness bug, which is why this third check sits at the gentlest severity.",
    "howToFix": [
      "Add a single <h1> to every page that lacks one: name the page's primary topic in it, since Google uses the H1 to disambiguate when the title tag is unclear.",
      "Where a page has two or more H1s, keep one and demote the rest to <h2>; the visual size can stay identical via CSS, only the markup level changes.",
      "Check that your hero title is a real <h1> tag and not a styled <div> or <span>: CSS that merely looks like a heading does not count and still trips the missing-H1 error.",
      "Break any page over 600 words into sections with <h2> sub-headings; aim for one H2 per distinct idea so Featured Snippet extractors have clear blocks to pull from.",
      "Fix the template, not the page: a missing or duplicated H1 in a pSEO layout repeats across every generated URL, so one markup change clears the entire cluster at once.",
      "Re-run the audit after editing the template to confirm all three checks (missing, duplicate, and 600-word-no-H2) clear together."
    ],
    "url": "https://pseolint.dev/rules/heading-structure"
  },
  {
    "ruleId": "content/image-alt-text",
    "slug": "image-alt-text",
    "category": "content",
    "title": "Image Alt Text, Catching Content Images That Ship With No Description",
    "oneLiner": "content/image-alt-text scans every <img> tag on a page, skips images you have explicitly marked decorative, and reports each URL where a content-bearing image carries no alt attribute at all, the accessibility gap WCAG 2.1 has required closing under success criterion 1.1.1 since June 5, 2018 and the one that keeps a page out of Google Images.",
    "whatItDetects": "content/image-alt-text reads every <img> tag in a page's HTML and asks one question of each: is this image content-bearing, and if so does it have an alt attribute at all? The rule parses the tag's attributes, then skips any image you have deliberately marked as decorative, role=\"presentation\" or role=\"none\", aria-hidden=\"true\", or an explicit empty alt=\"\". An empty alt is treated as an intentional signal that the image carries no information, so it is accepted, never flagged.\n\nThe rule fires only when the alt attribute is entirely missing from a content-bearing image, not when it is present but short, and not on images you told it to ignore. For each page it counts how many qualifying images lack alt, divides by the total content-bearing images on that page, and emits one summary finding per URL rather than one line per image. A sample of up to three image sources is attached so you can find the offenders fast.\n\nSeverity scales with how widespread the gap is on the page: when at least half of a page's content images are missing alt the finding is a warning; below that ratio it drops to info, on the logic that a single stray image is a smaller signal than a template that never binds the slot.",
    "howToFix": [
      "Add a descriptive alt attribute to every content-bearing <img> that conveys information: describe what the image shows, not the file name, and keep it to a natural phrase a screen reader can speak.",
      "For purely decorative images (dividers, background flourishes, spacer graphics) set alt=\"\" explicitly or add aria-hidden=\"true\" so the rule recognises the omission as intentional rather than forgotten.",
      "In a pSEO template, bind the alt text from the same data source that fills the rest of the page (the product name, the city, the edition size) so each generated image gets its own description instead of a static default.",
      "Never leave a templated alt at a literal placeholder like alt=\"image\" or the entity name alone; a default that repeats across every page is its own duplicate-content tell even though it technically passes this rule.",
      "Re-run the audit after fixing the template binding: because the finding is per page, a single corrected template binding clears the warning across the entire catalog at once.",
      "Spot-check with a screen reader or the browser accessibility tree to confirm the descriptions actually make sense when read aloud, not just that the attribute is present."
    ],
    "url": "https://pseolint.dev/rules/image-alt-text"
  },
  {
    "ruleId": "links/orphan-pages",
    "slug": "orphan-pages",
    "category": "links",
    "title": "Orphan Pages, URLs No Other Page Links To",
    "oneLiner": "links/orphan-pages scans every URL in the crawl, counts the inbound internal links pointing at each one, and fires at error severity on any page with exactly 0 of them, the dead-zone shape that leaves Googlebot unable to reach a URL through your own navigation, a structural gap the March 27, 2026 core update treats as a discoverability failure rather than a content one.",
    "whatItDetects": "links/orphan-pages builds one number for every page in the crawl: how many other pages in the same corpus link to it. It walks each parsed page, reads the inbound-link count the crawler accumulated while following internal hrefs, and flags any URL whose count is exactly 0. The root URL is exempted (your homepage is reached directly, not via an internal link) so the rule never accuses the front door of being unreachable.\n\nThe check is corpus-scoped, which is the detail that makes it honest. It only knows about pages the crawl actually visited and only counts links between those pages. A URL with zero inbound links is one that no page in the set references, meaning a crawler arriving at your homepage has no internal path to it. The page might still be reachable through your XML sitemap or an external backlink, but inside the site's own link graph it is an island.\n\nEvery orphan emits a single error-severity finding naming the URL and recommending you link to it from a relevant hub or index and add it to navigation. The rule reasons purely about reachability; it makes no judgement about whether the page's content is good, only about whether anything points at it.",
    "howToFix": [
      "Link every orphan from a relevant hub or category index so it joins the site's internal link graph and a crawler can actually reach it.",
      "Fix paginated or truncated index templates that list only the first N items: the missing children are usually the orphans, and crawlable pagination restores them all at once.",
      "Add the page to your primary or contextual navigation when it is genuinely important, so it earns inbound links from high-traffic parts of the site.",
      "Cross-link related items to each other, so a product, article, or location references its siblings instead of depending on one fragile index page.",
      "Re-crawl after wiring the links and confirm the inbound count is no longer 0: a sitemap entry alone does not clear this rule, because the rule measures internal links, not sitemap membership.",
      "For pages that should not exist as standalone URLs, consolidate or noindex them rather than leaving unreachable thin pages stranded in the corpus."
    ],
    "url": "https://pseolint.dev/rules/orphan-pages"
  },
  {
    "ruleId": "links/dead-ends",
    "slug": "dead-ends",
    "category": "links",
    "title": "Dead Ends, Pages With Zero Outbound Links to the Rest of Your Crawl",
    "oneLiner": "links/dead-ends flags every crawled page (the homepage aside) whose outbound links include zero URLs that point to another page in the same crawl, the forward-flow gap that strands Googlebot and traps link equity, a warning a model-railway shop's 1,400 product listings hit when each turnout and locomotive page links only out to a vendor, never deeper into the store.",
    "whatItDetects": "links/dead-ends walks every page in your audited corpus, skips the root URL, and for each remaining page counts how many of its resolved outbound links point to another page that is also in the crawl. The check is strict: a link only counts if its target is in the known-URL set and is not a self-link back to the same page. When that count lands at exactly zero, the page is a dead end and the rule emits a warning naming the URL.\n\nThe test is corpus-scoped, not page-local. A page can carry dozens of links to external vendors, social profiles, or PDFs and still be a dead end, because none of those targets is another crawled page on your own site. Forward flow is the only thing measured: does standing on this page give a crawler, or a reader, any path deeper into the rest of the corpus.\n\nSeverity is fixed at warning. A dead end is not a broken page or a thin page; it renders fine and may read well. It simply terminates the internal link graph at that node, so anything that travels along links, crawl reach and ranking signal alike, stops there instead of moving on to the next page.",
    "howToFix": [
      "Add contextual internal links from every leaf page to a handful of genuinely related crawled pages, so each node offers the crawler a path forward rather than a one-way valve.",
      "Link each product or article up to its parent category or hub page, which alone is usually enough to clear the warning while also restoring a route back into the broader corpus.",
      "Build a related-items or related-reading block into the page template, since dead ends on programmatic sites almost always trace to a template that renders only external links.",
      "Audit your link resolver: relative hrefs, JavaScript-injected menus, or trailing-slash mismatches can make real internal links resolve to URLs outside the known set, so a linked page still reads as a dead end.",
      "Distinguish a dead end from a deliberately terminal page like a checkout or thank-you screen, and exclude only those that should not feed the crawl, never the content pages you want indexed.",
      "Re-crawl after editing the template, because dead ends are usually template-wide: one fix to the shared listing layout clears the warning on hundreds of pages at once."
    ],
    "url": "https://pseolint.dev/rules/dead-ends"
  },
  {
    "ruleId": "links/link-depth",
    "slug": "link-depth",
    "category": "links",
    "title": "Link Depth, How Many Clicks From Home Before Googlebot Gives Up",
    "oneLiner": "links/link-depth runs a breadth-first search from your root URL and measures the shortest click-distance to every page, flagging anything past the default ceiling of 3 clicks as info and anything Googlebot cannot reach from the root at all as a warning, because a page Google crawls last is a page Google ranks last.",
    "whatItDetects": "links/link-depth treats your internal-link graph the way a crawler does. It seeds a breadth-first search at the root URL you audited, walks every internal link, and records for each page the shortest number of clicks it takes to arrive there. The BFS guarantees that distance is the minimum, so a page linked from both the homepage and a deep article is scored by its nearest path, not its farthest.\n\nTwo distinct findings come out of that single traversal. First, any page whose shortest click-distance exceeds maxClicks (default 3) is reported at info severity with a message naming the page and the depth it sits at. Three clicks is the conventional ceiling because it mirrors how deep a crawler will eagerly follow before a page starts competing for scarce budget.\n\nSecond, any page that has inbound internal links yet never gets visited by the BFS is reported at warning severity as unreachable-from-root. That gap means the page is referenced somewhere, but no chain of links actually connects it back to the root, so a crawler starting at the homepage would never find it.\n\nWhen the audit only sampled a subset of the site, the unreachable check is suppressed, because a missing path may be a sampling artifact rather than a real dead end; the depth measurement keeps running on whatever subgraph was fetched.",
    "howToFix": [
      "Link your deepest money pages directly from a hub or category page so the BFS reaches them in 2 to 3 clicks instead of 5 or 6.",
      "Audit any page reported as unreachable-from-root first; that is a structural island, and adding a single navigational link from a reachable page fixes it.",
      "Flatten deep taxonomies: collapse redundant intermediate index pages that add a click without adding value to a visitor or a crawler.",
      "Add contextual in-content links from popular shallow pages down to important deep ones, so equity has a short path to follow.",
      "Re-run the audit after restructuring, because moving one hub link can lift an entire subtree of pages back inside the 3-click ceiling at once.",
      "Do not rely on an XML sitemap to rescue a buried page: a sitemap aids discovery but does not pass the internal PageRank that depth controls."
    ],
    "url": "https://pseolint.dev/rules/link-depth"
  },
  {
    "ruleId": "links/cluster-connectivity",
    "slug": "cluster-connectivity",
    "category": "links",
    "title": "Cluster Connectivity, When a Directory of Pages Becomes a Topic Silo",
    "oneLiner": "links/cluster-connectivity groups every crawled URL by its parent directory, and for each cluster of 2 or more pages it checks whether a single internal crawl link enters from another cluster or leaves toward one, firing a warning when neither exists, because Google cannot diffuse authority into a directory that no other section of your site references or is referenced by.",
    "whatItDetects": "The rule keys every crawled URL to its parent directory using the same cluster logic the link family shares: /cheese/affinage/ and /cheese/rind/ collapse to the /cheese/ parent, so a cluster is simply the set of pages that live under one folder. It builds that map first, then only looks at clusters that hold 2 or more pages, because a lone page is an orphan question, not a connectivity one.\n\nFor each multi-page cluster it asks two narrow questions against the set of URLs the crawl actually knows about. First, outbound: does any page in the cluster carry a resolved internal href whose target resolves to a different cluster? Second, inbound: does any page outside the cluster link to any URL inside it? A link that stays within the same parent directory does not count for either test, internal-to-cluster links keep the silo sealed.\n\nWhen a cluster of 2 or more pages has neither a cross-cluster outbound link nor a cross-cluster inbound link, it is a sealed silo and the rule emits one warning naming the directory, the page count, and the affected URLs. A cluster with even a single link crossing its boundary in either direction passes.",
    "howToFix": [
      "Add at least one inbound link from a related section. A single contextual link from your catalog, blog, or navigation into the siloed directory is enough for a crawler to find and credit it.",
      "Add at least one outbound link from inside the cluster to another section. Linking out is half the test; a cluster that only receives links still reads as a one-way pocket until its own pages reference the rest of the site.",
      "Link on topical relevance, not in a footer dump. A contextual link from a genuinely related page passes far more authority and reads as editorial rather than as a sitewide boilerplate block.",
      "Audit your navigation for whole sections it omits. Silos usually form when a directory was built after the main nav was frozen and never got wired back into it.",
      "Re-crawl after adding the links. Because the rule only needs one crossing edge in each direction, a small number of well-placed links can clear several siloed clusters at once.",
      "Treat the warning as a discoverability prompt, not a penalty. The pages are not flagged as low quality; they are flagged as unreachable, which is usually a quick fix with outsized traffic upside."
    ],
    "url": "https://pseolint.dev/rules/cluster-connectivity"
  },
  {
    "ruleId": "cannibal/url-pattern",
    "slug": "url-pattern",
    "category": "cannibal",
    "title": "URL Pattern Cannibalization, When Two Slugs Are the Same Words Reordered",
    "oneLiner": "cannibal/url-pattern splits each URL's last slug on hyphens, sorts the tokens, and flags at info severity any two pages in the same directory whose sorted token sets match exactly, the reordered-slug keyword cannibalization Google has resolved by collapsing competing URLs to one canonical result since well before its March 2026 core update.",
    "whatItDetects": "cannibal/url-pattern looks for two URLs that are, word for word, the same page wearing a different word order. For every page it takes the final path segment (the slug after the last slash, trailing slashes removed) splits it on hyphens, drops empty tokens, and sorts what remains alphabetically. Two slugs that differ only in the order of their words produce an identical sorted token list.\n\nThe rule then compares pages pairwise, but only within the same parent directory: the path up to that last slash must match, and it must not be empty. When two distinct URLs in one directory collapse to the same sorted tokens, the rule fires once at info severity, naming both URLs and reporting that they carry the same tokens in a different order. Pages in different directories never compare against each other, and a slug with no tokens is skipped. The match is exact after sorting (not fuzzy) so it fires only when the two slugs really are the same word set reshuffled.",
    "howToFix": [
      "Pick one canonical token order for every slug your builder emits, so the same record can never mint both /moog-analog-oscillator and /oscillator-moog-analog.",
      "Add a 301 redirect from the reordered twin to the canonical URL, collapsing the pair into one address before the link equity finishes splitting.",
      "Set a rel=canonical on any duplicate you cannot redirect, pointing every reordered variant at the single slug you want Google to rank.",
      "Audit the slug-generation code, not the pages: the reorder almost always comes from a builder concatenating attribute tokens in whatever order the data arrives.",
      "Sort or fix the token order at write time in your data pipeline, so new listings are minted in canonical order and the pair never appears again.",
      "Check internal links and your sitemap for both variants, and repoint every reference at the canonical slug so crawlers stop discovering the twin."
    ],
    "url": "https://pseolint.dev/rules/url-pattern"
  },
  {
    "ruleId": "aeo/freshness-signals",
    "slug": "freshness-signals",
    "category": "aeo",
    "title": "Freshness Signals, When a Page Gives AI Engines No Sign It Is Current",
    "oneLiner": "aeo/freshness-signals checks every page for a real modification signal (a JSON-LD dateModified, an article:modified_time meta tag, or a visible 'Last updated' line) warns at medium confidence when none exists, then drops to an info note when the best date it can parse is older than the staleness default of 180 days Google has long associated with how AI Overviews weigh recency.",
    "whatItDetects": "aeo/freshness-signals asks one question of every crawled page: does it carry evidence that it has been touched recently. The rule looks for a true modification signal in three places, a dateModified field anywhere in the page's JSON-LD (found by a recursive walk), a modification meta tag (article:modified_time, last-modified, dc.date.modified, or a <time datetime> element), or visible 'Last updated', 'updated on', 'revised', or 'last modified' text in the rendered content.\n\nA datePublished alone is deliberately not enough. A page born in 2019 and never edited has a publication date but no modification signal, so it falls through to a warning at medium confidence, medium because evergreen pages like an about, pricing, or policy page may legitimately omit a modified date, and re-stamping them would mislead readers.\n\nWhen a modification signal does exist, the rule parses the best date it can find and measures its age. If that age exceeds maxStaleDays (180 days by default) it emits an info finding at low confidence, because stale by the clock is not always stale by meaning. The two findings sit at different severities on purpose: a missing signal is a warning, an old-but-present date is only an info note.",
    "howToFix": [
      "Add a real dateModified to your JSON-LD schema and bump it whenever the page's underlying data changes, not just when a human edits the prose.",
      "Render a visible 'Last updated: YYYY-MM-DD' line in the page body so both readers and AI engines see the freshness claim without parsing schema.",
      "Wire the modified timestamp to your data source for pSEO templates, so a forecast page that repulls every 6 hours stamps the moment it actually regenerated.",
      "Keep your sitemap <lastmod> accurate and aligned with the on-page date: a contradictory lastmod is worse than none, since it tells the crawler your timestamps cannot be trusted.",
      "Leave genuinely evergreen pages alone: an about, pricing, or policy page that has not changed should not carry a fake recent date that would mislead a reader.",
      "Refresh the body, not just the date, on pages older than the 180 days default whose information has actually moved on, then bump dateModified to reflect the real edit."
    ],
    "url": "https://pseolint.dev/rules/freshness-signals"
  },
  {
    "ruleId": "aeo/llms-txt",
    "slug": "llms-txt",
    "category": "aeo",
    "title": "llms.txt, A Draft Convention for Guiding AI Engines, Checked at Your Origin",
    "oneLiner": "llms.txt is a draft, low-adoption convention proposed in September 2023 and championed by Jeremy Howard at Answer.AI, so pseolint runs this as a low-confidence, informational site-level check that fetches /llms.txt once at your origin and verifies 3 shape rules, treating a missing file as a missed opportunity worth roughly 1 hour of work, never a defect.",
    "whatItDetects": "This is a site-level check, not a per-page one: it runs exactly once against your origin. pseolint takes the source URL, derives its origin, requests `${origin}/llms.txt` with a 10 second timeout, and only proceeds for http and https targets. If the request fails, times out, or returns a non-200 status, the file is treated as absent.\n\nWhen the file is present, pseolint runs three deliberately lenient shape checks drawn from the llmstxt.org proposal. First, the opening non-empty line must be an `# ` H1 title (lines that start with `#` but carry no title text are skipped, not rejected). Second, the file must contain at least one `## ` section heading. Third, it must list at least one markdown link of the form `- [Title](https://...)` somewhere under a section. A file that satisfies all three passes silently.\n\nA missing file and a malformed file both surface the same low-confidence, informational finding, one tells you nothing exists at the origin, the other names which of the three rules failed. The check is intentionally forgiving because the specification is still evolving; it rejects only obvious garbage.",
    "howToFix": [
      "Create a plain-text file at the root of your origin, served as /llms.txt, that opens with a single `# Project Name` H1 title on the first non-empty line.",
      "Add a short blockquote summary under the title, then break your content into `## ` sections such as Getting Started, API Reference, Guides, and Releases.",
      "Under each section, list your most citable pages as markdown links in the form `- [Quickstart](https://...): one-line description` so an engine can read both the link and its purpose.",
      "Point the links at canonical, current pages (your live quickstart, API reference, SDK guides, and changelog) not deep-archived or redirecting URLs.",
      "Keep it in sync with releases: a stale llms.txt that omits a new major version or a renamed code sample misleads engines more than having none at all.",
      "Validate against the format described at llmstxt.org and re-run the audit; a passing file is silent, so no finding means the three shape checks are satisfied."
    ],
    "url": "https://pseolint.dev/rules/llms-txt"
  },
  {
    "ruleId": "aeo/crawler-access",
    "slug": "crawler-access",
    "category": "aeo",
    "title": "Crawler Access, Is Your robots.txt Blocking AI Answer Engines?",
    "oneLiner": "aeo/crawler-access parses your robots.txt user-agent by user-agent and checks 8 named AI crawlers (GPTBot from OpenAI, ClaudeBot from Anthropic, PerplexityBot, Google-Extended, and four more) warning once per fully blocked bot and escalating to an error only when every one is disallowed, so blocking them stays a deliberate choice you make, not a verdict the rule hands down.",
    "whatItDetects": "The rule reads your robots.txt and parses it into a map of user-agent to its Disallow patterns, lowercasing every agent name so the lookup is case-insensitive and stacking consecutive User-agent lines that share one rule block. It then walks a default list of 8 AI crawler user-agents: GPTBot (OpenAI), ChatGPT-User (OpenAI), ClaudeBot (Anthropic), PerplexityBot (Perplexity), Bytespider (ByteDance), Google-Extended (Google), CCBot (Common Crawl), and Applebot-Extended (Apple). You can override this list in pseolint.config.ts to add or remove agents.\n\nFor each crawler the rule asks one question: is this bot fully disallowed? A bot counts as blocked when its own block contains a root Disallow (`Disallow: /` or `Disallow: /*`), or when it has no rule of its own and falls back to a wildcard `User-agent: *` block that is itself fully disallowed. A bot with its own narrower block (say `Disallow: /admin/`) is not counted as blocked, because the rest of the site is still readable.\n\nEvery fully blocked crawler produces one warning naming that bot. If the count of blocked crawlers equals the full configured list (every AI agent disallowed) the warnings collapse into a single error instead, because total blocking is an unambiguous, site-wide decision worth one clear finding rather than 8 scattered ones.",
    "howToFix": [
      "Open robots.txt and find every block with a root `Disallow: /`. For each named AI crawler you want quotable, delete that root rule so the bot can reach your public pages again.",
      "If you only meant to hide private areas, replace `Disallow: /` with the specific paths (for example `Disallow: /drafts/` and `Disallow: /admin/`) so the rest of the site stays crawlable by answer engines.",
      "Decide deliberately which bots you keep out. Blocking a scraper like Bytespider while allowing GPTBot and ClaudeBot is a valid stance; just confirm it is the stance you actually want.",
      "Remember the wildcard fallback: a `User-agent: *` block with `Disallow: /` silently blocks every AI crawler that has no rule of its own. Give bots you want to allow their own narrower block to escape it.",
      "After editing, re-run the audit. The rule downgrades from a site-wide error to per-bot warnings to silence as you reopen access, so you can watch each decision take effect."
    ],
    "url": "https://pseolint.dev/rules/crawler-access"
  },
  {
    "ruleId": "aeo/faq-coverage",
    "slug": "faq-coverage",
    "category": "aeo",
    "title": "FAQ Coverage, Question Content That Ships With No FAQPage Schema",
    "oneLiner": "aeo/faq-coverage flags any page that reads like an FAQ (at least 2 question-phrased H2 headings starting with how, what, or why, or a /faq, /how-to, or /what-is URL path) yet ships no FAQPage or HowTo JSON-LD, the structured-data gap that matters far more for AI extraction since Google narrowed FAQ rich results to government and health sites in August 2023.",
    "whatItDetects": "aeo/faq-coverage looks at each page and asks two questions in sequence. First, does this page look like FAQ or how-to content? It looks that way if 2 or more of its H2 headings are phrased as questions, a heading that ends in a question mark, or one that opens with a question word like how, what, why, when, where, who, can, does, is, are, should, or which, or if the URL path matches a question pattern such as /faq, /how-to-, /what-is-, /guide-, or /questions. The trigger threshold is the faqMinQuestionHeadings option, which defaults to 2.\n\nSecond, if the page looks like FAQ content, does it carry the structured data that declares it? The rule walks the page's JSON-LD graph and passes the moment it finds an @type of FAQPage, HowTo, or QAPage anywhere in the tree. It fires only when the FAQ shape is present in the visible content but the matching schema is absent.\n\nThe finding lands at info severity with medium confidence. Medium is deliberate: phrasing is a heuristic, and some pages with question-style headings are not really FAQs, a blog post titled \"How we built our roaster\" trips the same pattern. So the rule offers the schema as an opportunity, never as a verdict.",
    "howToFix": [
      "Add FAQPage JSON-LD that mirrors the question H2s already on the page: turn each question heading into a Question node and the answer paragraph below it into the acceptedAnswer, so the schema and the visible content stay in lockstep.",
      "Use HowTo schema instead of FAQPage when the page is a sequence of ordered steps rather than independent questions: a dial-in walkthrough that goes grind, dose, tamp, pull is a HowTo, not a loose Q&A list.",
      "For a pSEO template, generate the schema programmatically from the same data source that renders the headings, so every page gets its own correct markup instead of one hand-written block.",
      "Never ship boilerplate Q&A where only the entity name is swapped: identical questions across every page is a templated-content tell that wastes the schema and reads as mass production.",
      "Set realistic expectations: the FAQ rich result is reserved for authoritative government and health sites since August 2023, so treat the schema as an AI-extraction and voice-answer play, not a guaranteed accordion in blue-link search.",
      "Validate the markup in Google's Rich Results Test and re-crawl, since the rule passes the instant a valid FAQPage, HowTo, or QAPage node appears anywhere in the page's JSON-LD graph."
    ],
    "url": "https://pseolint.dev/rules/faq-coverage"
  },
  {
    "ruleId": "aeo/summary-bait",
    "slug": "summary-bait",
    "category": "aeo",
    "title": "Summary Bait, When a Page Front-Loads Every Fact and Leaves the Body Hollow",
    "oneLiner": "aeo/summary-bait fires when 70% or more of a page's citable facts are crammed into its first 150 words and nothing fresh waits below, a low-confidence warning that the page is shaped for an AI Overviews snippet Google can lift whole rather than for a reader who scrolls past the opener.",
    "whatItDetects": "aeo/summary-bait measures one ratio: of all the citable facts on a page, what fraction sits in the first 150 words? The rule extracts facts with the same patterns aeo/citable-facts uses (dollar amounts, percentages, timeframes like '11 days' or '4 weeks', month-day dates, and form numbers) once across the whole page and once across the opener alone, then divides the opener count by the full count.\n\nWhen 70% or more of the page's facts land in that opener, and the page has at least 3 facts to begin with, the rule warns at low confidence. Two gates keep it quiet on healthy pages. First, the opener must already pass aeo/answer-first (a complete, fact-bearing lead) because front-loading a clear answer is good, not a fault. Second, the page must carry no interactive, downloadable, or gated value below the fold: a foraging-calendar widget, a printable spore-print key, or a sign-in-to-continue block all mean there is a real reason to scroll, so the rule stays silent. Only the overlap (strong opener, everything cited up top, nothing new beneath) trips it.",
    "howToFix": [
      "Keep the answer-first opener, but move the supporting numbers below it. The lead should resolve the question; the dated season tables, yield figures, and method steps belong in sections a reader scrolls to reach.",
      "Add value a summary cannot carry. A foraging-calendar widget, a printable spore-print identification key, or a region-specific harvest map gives both the reader and the rule a genuine reason the page exists beyond its opener.",
      "Redistribute citable facts so concentration drops under the 70% threshold. If four of five figures sit in the first 150 words, push two of them into a 'Full season breakdown' section deeper on the page.",
      "Replace padding prose with new information. The body that merely restates the opener in looser words is exactly what flags the page; every section below the fold should add a fact the snippet did not.",
      "Gate or download the genuinely valuable asset. A sign-in-to-save patch log or a downloadable hedgerow checklist counts as below-fold value the rule respects, because an AI Overview cannot reproduce it.",
      "Re-run the audit after rebalancing. The finding clears the moment opener concentration falls below 70% or the page gains real interactive value below the fold."
    ],
    "url": "https://pseolint.dev/rules/summary-bait"
  },
  {
    "ruleId": "content/translation-no-op",
    "slug": "translation-no-op",
    "category": "content",
    "title": "Translation No-Op, Locale Folders That Were Never Actually Translated",
    "oneLiner": "content/translation-no-op groups URLs that differ only by a leading locale segment like /en/ or /fr/, computes a 64-bit SimHash of each extracted body, and fires an error the moment any pair scores at or above 95% similarity, the fake-i18n pattern Google has told site owners to fix with real hreflang pairs, not duplicated English.",
    "whatItDetects": "content/translation-no-op catches a specific failure of programmatic internationalisation: a site ships /en/, /fr/, /de/ folders that look multilingual in the URL but carry the same untranslated body on every locale.\n\nThe rule reads each page's path and matches a leading locale segment with a regular expression covering two-letter codes and region variants, /en/, /fr/, /it/, /fr-ca/. Pages without a locale prefix are skipped. It strips that segment to a base path so /en/openings and /fr/openings both collapse to /openings, then buckets every locale variant under that shared base path. A bucket with fewer than two members is ignored, because one lone locale is not a translation problem.\n\nWithin each bucket it computes a 64-bit SimHash from the extracted main content text, measures Hamming distance between every variant pair, and converts that distance to a similarity score in [0,1]. If any pair scores at or above the 0.95 threshold, the rule emits one error per cluster naming the locale count, the base path, and the exact similarity percentage so you can see how identical the variants really are.",
    "howToFix": [
      "Translate the body for real, not just the title and nav; the SimHash is computed on extracted main content, so a translated heading over an English article still trips the rule at 95%.",
      "If a locale was never meant to ship, delete the untranslated folder and remove its hreflang entry rather than leaving a duplicate live under a foreign tag.",
      "Where you genuinely cannot translate yet, redirect every untranslated locale variant to the canonical URL and keep hreflang only on the canonical until real translations exist.",
      "Audit your i18n pipeline for partial coverage: a template that translated 4 of 12 locales leaves 8 folders of duplicated source language that this rule will flag cluster by cluster.",
      "Re-run after each translation pass: the rule fires once per cluster of near-identical variants, so clearing one base path does not silence the others until their bodies actually diverge."
    ],
    "url": "https://pseolint.dev/rules/translation-no-op"
  },
  {
    "ruleId": "content/regurgitated-content",
    "slug": "regurgitated-content",
    "category": "content",
    "title": "Regurgitated Content, When Your Directory Is Just the Google Places API Reskinned",
    "oneLiner": "content/regurgitated-content is a low-confidence v1 heuristic that fires a warning when a page shows at least 2 of 5 Google-Places-regurgitation tells, Powered by Google attribution, googleusercontent images over 60%, a Static Maps embed, Places API JavaScript, or an aggregator footprint of 5 or more unsigned star-rating blocks.",
    "whatItDetects": "content/regurgitated-content looks for one shape: a page that lifts business names, reviews, addresses, and photos straight from the Google Places API and presents them as a directory with nothing of its own added on top. It reads five independent signals per page and fires only when at least 2 of them are present.\n\nThe signals are specific. (1) Google Places attribution, a 'powered by google' string, or a noopener anchor pointing at google.com/maps. (2) Google images dominate, once a page has 3 or more images, the rule fires this signal when over 60% of them are hosted on googleusercontent.com, the Places photo endpoint, or Street View pixels. (3) Static Maps or Maps embed, a maps.googleapis.com/maps/api/staticmap source, or a google.com/maps/embed iframe. (4) Places API JavaScript, a google.maps.places.PlacesService or AutocompleteService marker in the markup. (5) Aggregator footprint, 5 or more elements carrying a star rating (Unicode stars, a 4.5/5 fraction, or the word 'stars') on a page that shows fewer than 2 of 3 E-E-A-T signals (author, published date, an /about link).\n\nSeverity is fixed at warning and confidence is low. This is a v1 heuristic that reasons about structure, never about a licence: it cannot read a Places API contract or know whether you have permission. It only sees the fingerprint that raw redistribution leaves behind.",
    "howToFix": [
      "Add proprietary substance the API does not hold (original tasting notes, a ranked verdict, a first-person visit log) so the page is more than a redistribution layer.",
      "Shoot and host your own photography. When your own images outnumber googleusercontent.com hero shots, the Google-images-dominate signal stops firing and the page stops looking lifted.",
      "Keep one attributed Google review if you like, but write your own editorial summary alongside it rather than republishing a wall of 5-plus star-rating blocks verbatim.",
      "Attach E-E-A-T: a named byline, a published date, and an /about page describing how you evaluate each venue, which both clears the aggregator-footprint signal and answers the trust question.",
      "Use the embedded map as a convenience, not the content: one Static Maps embed is fine when the words around it are yours and not the API's.",
      "If a page genuinely has nothing to add beyond the Places data, merge it or cut it rather than shipping a thin reskin that competes with Google using Google's own facts."
    ],
    "url": "https://pseolint.dev/rules/regurgitated-content"
  },
  {
    "ruleId": "content/common-phrase-reuse",
    "slug": "common-phrase-reuse",
    "category": "content",
    "title": "Common Phrase Reuse, When pSEO Clichés Pile Up On One Page",
    "oneLiner": "content/common-phrase-reuse scans each page against a bundled list of roughly 42 pSEO marketing clichés grouped into 5 categories (location filler, generic-marketing superlatives, aggregator phrasing, fake-authority claims, and filler hedges) and raises one low-confidence warning the moment 3 or more distinct phrases from that list appear, a speculative density signal Google's helpful-content guidance has weighted since 2024.",
    "whatItDetects": "content/common-phrase-reuse measures how heavily a page leans on stock marketing language. It carries a bundled list of roughly 42 pSEO clichés split across 5 categories: location filler, generic-marketing superlatives, aggregator phrasing, fake-authority claims, and filler hedges. The failing example below shows the kind of phrasing each category covers, so this explainer keeps the quoted samples inside that illustration rather than scattering them through the prose.\n\nFor each page the rule lower-cases the main content text and checks which bundled phrases appear as substrings. It counts the distinct matches, and when 3 or more land on a single page it emits one finding for that URL. The severity is a warning and the confidence is deliberately low: matching a fixed phrase list is a crude proxy, so the rule names the first few matches it found and leaves the judgement to you rather than asserting the page is bad.",
    "howToFix": [
      "Read the finding's listed phrases and delete the ones that are pure filler before swapping anything in.",
      "Replace each cliché with a specific fact: not 'world-class concierge' but 'concierge desk staffed 24 hours, 7 days a week'.",
      "Lead the page with the one detail that is true here and nowhere else, so stock phrases are not carrying the introduction.",
      "Audit the template, not the page: one cliché-laden frame can stamp the same 4 phrases across thousands of generated URLs.",
      "Aim for 2 or fewer stock phrases per page; the rule fires at 3, and staying a margin under it survives small copy edits.",
      "Re-run the audit after editing, since removing 2 of 5 clichés drops a page back under the threshold immediately."
    ],
    "url": "https://pseolint.dev/rules/common-phrase-reuse"
  },
  {
    "ruleId": "content/wikipedia-paraphrase",
    "slug": "wikipedia-paraphrase",
    "category": "content",
    "title": "Wikipedia Paraphrase, When Your Page Is Just the Encyclopedia, Reworded",
    "oneLiner": "content/wikipedia-paraphrase fires a low-confidence warning the moment a page shares 40% or more of its three-word phrases with a bundled Wikipedia reference corpus, the trigram-overlap point at which Google's helpful-content framing reads a URL as reworded encyclopedia rather than the original analysis a March 2024 audit rewards.",
    "whatItDetects": "content/wikipedia-paraphrase asks one narrow question of each page: how much of your prose is just Wikipedia, lightly reworded? The rule tokenises the main content text (lower-cased, punctuation stripped, split on whitespace) and slides a three-word window across it to produce a list of trigrams. Each trigram is checked against a bundled Wikipedia reference corpus stored as a compact bloom filter (65,536 bits, 3 FNV-1a hash functions, roughly a 5% false-positive rate over about 10,000 curated trigrams). The paraphrase rate is the fraction of a page's trigrams that hit the corpus.\n\nWhen that rate reaches the 0.40 threshold, the rule emits one finding per qualifying page at warning severity and low confidence, reporting the exact overlap percentage so you can sort worst-first. Pages with fewer than three tokens score zero and are skipped. The framing is deliberate: paraphrased encyclopedic content adds nothing original to the web, so a page that is 40% recycled Wikipedia phrasing is, for ranking purposes, a page that already exists.\n\nThe heuristic is honest about its limits; it is a low-confidence signal precisely because the corpus is bundled and finite, and a page about a genuinely encyclopedic subject can share common phrasing without copying anything.",
    "howToFix": [
      "Lead with first-hand observation the encyclopedia cannot have: the dig site, the exact sediment layer, the prep tools, the measured dimensions of your actual specimen.",
      "Replace reworded background with two or three linked sentences, then send the reader to Wikipedia for the textbook taxonomy rather than rephrasing it on your page.",
      "Add page-specific facts that exist nowhere else: your matrix-removal technique, the failed prep that cracked a trilobite, the locality coordinates, the date you collected it.",
      "Photograph and describe your own material. A theropod tooth you found, scaled and lit, is content no corpus contains; a reworded description of theropod dentition is not.",
      "Re-run the audit and sort by overlap percentage. Clear pages above 45% first; those are almost entirely reference text and need the most original substance grafted in.",
      "Treat the warning as a prompt, not a verdict. On a legitimately encyclopedic topic the heuristic can over-fire, so confirm the page actually reads as reworded Wikipedia before rewriting it."
    ],
    "url": "https://pseolint.dev/rules/wikipedia-paraphrase"
  },
  {
    "ruleId": "content/value-add",
    "slug": "value-add",
    "category": "content",
    "title": "Value-Add Score, The Composite That Reads Seven Other Rules",
    "oneLiner": "content/value-add is a second-pass composite that reads seven other rules' findings, originality, freshness, citable facts, the four-category E-E-A-T count, translation, cliche reuse, and Wikipedia paraphrase, weights each at one-seventh, averages them into a single 0-to-1 score, and fires an error below 50% or a critical below 30%, the synthesis SpamBrain has rewarded since the March 5, 2024 update.",
    "whatItDetects": "content/value-add does not parse a page. It runs after every other rule has finished and reads their findings, turning seven separate originality checks into one number. Each signal is scored 0, 0.5, or 1 for the page, and the rule takes the plain average, every signal weighted at one-seventh, about 14%.\n\nThe seven signals are: originality (1 unless content/regurgitated-content fired here, then 0), freshness (from aeo/freshness-signals, 1 if silent, 0.5 at warning, 0 otherwise), citable facts (from aeo/citable-facts, 1 if silent, 0.5 at info or warning, 0 otherwise), E-E-A-T (a four-category count, 1 at four signals, 0.5 at two or three, 0 below two), translation (0 if content/translation-no-op named this page, else 1), cliche reuse (0 if content/common-phrase-reuse fired, else 1), and Wikipedia paraphrase (0 if content/wikipedia-paraphrase fired, else 1).\n\nThe average is the value-add score. Below 50% the rule fires one finding per page at error severity; below 30% it escalates that finding to critical. Confidence is fixed at medium.",
    "howToFix": [
      "Lift originality first: rewrite any copy that tripped regurgitated-content into a page-specific tasting note, because that signal is binary and recovering it adds a full one-seventh to the score.",
      "Add a real published or updated date so the freshness signal climbs from 0 toward 1: an undated page scores zero on a signal that costs one line of markup to fix.",
      "Bind citable facts a buyer can quote (a harvest window, a steeping temperature, an estate elevation) so the citable-facts signal stops scoring zero on a page of pure prose.",
      "Reach four E-E-A-T categories (a byline, an about link, a date, and a sources block) since two or three only earns 0.5 while four earns the full point.",
      "Clear cliche reuse and any translation-no-op flag: both are binary signals, and a page padded with common phrases or a hollow auto-translation each forfeits a full one-seventh.",
      "Re-run the audit after fixing the worst two signals: because the score is an average, recovering two zeros to ones usually moves a 43% page past the 50% floor in one pass."
    ],
    "url": "https://pseolint.dev/rules/value-add"
  }
];
