/**
 * The checks pseolint deliberately does NOT run.
 *
 * Single source of truth for both the public /folklore page and the
 * contributor-facing docs/folklore.md (regenerated by
 * `bun run gen:folklore` from this array, so the two can never drift).
 *
 * A linter earns trust by what it refuses to flag as much as by what it
 * catches. Every entry cites the primary source that contradicts the claim;
 * a claim whose only support is an SEO blog or a vendor checklist belongs
 * here rather than in the engine.
 */

export type FolkloreVerdict = "False" | "Outdated" | "Unsupported" | "Misread" | "Obsolete";

export interface FolkloreEntry {
  /** The claim as people actually repeat it. */
  claim: string;
  verdict: FolkloreVerdict;
  /** What the primary source actually says, and what to check instead. */
  reality: string;
  /** Human-readable citation title. */
  sourceTitle: string;
  sourceUrl: string;
  /** Rule IDs that cover the real, documented failure mode. */
  insteadRules?: string[];
}

export const FOLKLORE: readonly FolkloreEntry[] = [
  {
    claim: "Meta descriptions must stay under 155 to 160 characters",
    verdict: "False",
    reality:
      "Google's snippet documentation says it outright: there is no limit on how long a meta description can be. Truncation is a display behaviour that varies with device width, not an indexing event. The documented failures are a MISSING description (Google then writes the snippet itself) and one templated description repeated across a whole cluster.",
    sourceTitle: "Google Search Central: control your snippets",
    sourceUrl: "https://developers.google.com/search/docs/appearance/snippet",
    insteadRules: ["content/meta-description-presence", "content/meta-uniqueness"],
  },
  {
    claim: "Title tags over 60 characters get penalised or rewritten",
    verdict: "False",
    reality:
      "No character limit is documented anywhere. SERP cropping is pixel-based and display-side. Google does document what triggers a REWRITTEN title, and none of it is length: half-empty template fields, boilerplate repeated across a cluster, stale year numbers, titles that do not match the page. Those are template smells worth catching.",
    sourceTitle: "Google Search Central: influencing your title links",
    sourceUrl: "https://developers.google.com/search/docs/appearance/title-link",
    insteadRules: ["content/title-uniqueness"],
  },
  {
    claim: "og:description should be 70 characters",
    verdict: "Unsupported",
    reality:
      "No such number exists in any specification. Meta's sharing guide says a description is usually between 2 and 4 sentences; ogp.me asks for one to two sentences. Open Graph tags are not a ranking input at all, they shape the social and AI-summary card. What IS in the spec and widely missed: og:type and og:url are required properties.",
    sourceTitle: "ogp.me: the Open Graph protocol",
    sourceUrl: "https://ogp.me/",
    insteadRules: ["tech/og-completeness"],
  },
  {
    claim: "Search engines can only process 2 MB of total website size",
    verdict: "Misread",
    reality:
      "A real number attached to the wrong object. Googlebot's documented limit is 2 MB per fetched FILE, uncompressed: every HTML page, stylesheet and script gets its own budget, and PDFs get 64 MB. There is no total-site or total-page-weight crawl ceiling. A 21 MB page whose HTML is 112 kB has a Core Web Vitals problem, not a crawl-truncation one.",
    sourceTitle: "Google Search Central: Googlebot",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    insteadRules: ["tech/html-size", "tech/core-web-vitals"],
  },
  {
    claim: "Googlebot indexes the first 15 MB of your HTML",
    verdict: "Outdated",
    reality:
      "This one was true. The 15 MB figure lived in Google's documentation for years and most SEO tools still cite it. The February 2026 revision of the Googlebot page cut the documented per-file crawl limit to 2 MB. Folklore and fact swap places when the source document moves, which is why every rule here links to the living doc rather than a summary of it.",
    sourceTitle: "Google Search Central: Googlebot",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    insteadRules: ["tech/html-size"],
  },
  {
    claim: "A missing meta keywords tag hurts your ranking",
    verdict: "False",
    reality:
      "Google's supported-tags page lists keywords as a tag it does not use, with no effect on indexing or ranking at all, and it has said so publicly since 2009. Any audit that still flags a missing keywords tag is dating itself.",
    sourceTitle: "Google Search Central: meta tags Google supports",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/special-tags",
  },
  {
    claim: "A wrong or missing html lang attribute is an SEO problem",
    verdict: "Misread",
    reality:
      "Google is explicit that it does not use code-level language information such as lang attributes, and detects language from visible content instead. The consequence cuts the other way: when your declared language and your actual content diverge, Google indexes by what it DETECTED, so the declared targeting silently fails. The attribute still matters for accessibility.",
    sourceTitle: "Google Search Central: managing multi-regional sites",
    sourceUrl:
      "https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites",
    insteadRules: ["tech/language-mismatch"],
  },
  {
    claim: "Sitemaps need priority and changefreq values",
    verdict: "False",
    reality:
      "Google documents that it ignores both. It does use lastmod, but only when the value is consistently and verifiably accurate. A sitemap that stamps every URL with the same generated timestamp teaches Google to distrust the one sitemap field that actually works.",
    sourceTitle: "Google Search Central: build and submit a sitemap",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap",
    insteadRules: ["tech/sitemap-hygiene"],
  },
  {
    claim: "Paginated archives need rel=next and rel=prev",
    verdict: "Obsolete",
    reality:
      "Google retired rel=next/prev as an indexing signal in 2019, years after most checklists canonised it. Bing still reads it, so it is not harmful, but adding it for Google is cargo cult.",
    sourceTitle: "Google Search Central: pagination and incremental page loading",
    sourceUrl:
      "https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading",
  },
  {
    claim: "Pages need 300 or more words to rank",
    verdict: "False",
    reality:
      "Google's helpful-content guidance answers this in its own words: are you writing to a particular word count because you heard Google has a preferred one? No, they do not. Word-count floors exist in SPAM detection at template scale, where a thousand 40-word pages differing by one city name is a doorway pattern, but that is a policy-risk signal rather than a per-page ranking factor.",
    sourceTitle: "Google Search Central: creating helpful content",
    sourceUrl: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    insteadRules: ["spam/thin-content", "content/unique-value"],
  },
  {
    claim: "Multiple meta description tags trigger a penalty",
    verdict: "Unsupported",
    reality:
      "Neither Google's documentation nor Lighthouse checks for it. Duplicated tags carrying different content are undefined behaviour worth tidying, but the place duplicates genuinely hurt is robots directives: Google applies the MOST RESTRICTIVE rule it finds across meta robots, meta googlebot and the X-Robots-Tag header, so one forgotten noindex in a conflicting pair silently wins.",
    sourceTitle: "Google Search Central: robots meta tag specifications",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag",
    insteadRules: ["tech/meta-robots-conflict"],
  },
  {
    claim: "An hreflang set is invalid without x-default",
    verdict: "Unsupported",
    reality:
      "Google's wording is consider adding x-default: a recommendation, not a requirement. What the same page does document as fatal is invalid codes. en_US with an underscore, jp where a language code belongs, en-UK when the United Kingdom is GB: each makes Google ignore the annotation entirely, with no error surfaced anywhere.",
    sourceTitle: "Google Search Central: localized versions of your pages",
    sourceUrl: "https://developers.google.com/search/docs/specialty/international/localized-versions",
    insteadRules: ["tech/hreflang-validity", "tech/hreflang-consistency"],
  },
  {
    claim: "CSS complexity hurts your ranking",
    verdict: "Unsupported",
    reality:
      "Rule counts, duplicated selectors, !important usage and vendor prefixes have no documented ranking role. They matter through exactly two documented mechanisms: a single file blowing past the per-file fetch limit, or rendering slow enough to degrade Core Web Vitals. Fix those two and selector count is a code-review topic rather than an SEO one.",
    sourceTitle: "Google Search Central: understanding page experience",
    sourceUrl: "https://developers.google.com/search/docs/appearance/page-experience",
    insteadRules: ["tech/html-size", "tech/core-web-vitals"],
  },
];
