/**
 * The checks pseolint deliberately does NOT run.
 *
 * Single source of truth for both the public /folklore page and the
 * contributor-facing docs/folklore.md (regenerated by
 * `bun run gen:folklore` from this array, so the two can never drift).
 *
 * A linter earns trust by what it refuses to flag as much as by what it
 * catches. Every entry cites the primary source that contradicts the claim;
 * a claim whose only support is an SEO blog or a vendor checklist belongs
 * here rather than in the engine.
 */

export type FolkloreVerdict = "False" | "Outdated" | "Unsupported" | "Misread" | "Obsolete";

export interface FolkloreEntry {
  /** The claim as people actually repeat it. */
  claim: string;
  verdict: FolkloreVerdict;
  /** What the primary source actually says, and what to check instead. */
  reality: string;
  /** Human-readable citation title. */
  sourceTitle: string;
  sourceUrl: string;
  /**
   * Additional primary sources, when the entry rests on more than one. Every
   * claim in `reality` must be traceable to `sourceUrl` or to one of these; a
   * sentence that cites neither belongs in neither place.
   */
  alsoSee?: readonly { title: string; url: string }[];
  /** Rule IDs that cover the real, documented failure mode. */
  insteadRules?: string[];
}

export const FOLKLORE: readonly FolkloreEntry[] = [
  {
    claim: "Meta descriptions must stay under 155 to 160 characters",
    verdict: "False",
    reality:
      "Google's snippet documentation says it outright: there is no limit on how long a meta description can be. Truncation is a display behaviour that varies with device width, not an indexing event. The documented failures are a MISSING description (Google then writes the snippet itself) and one templated description repeated across a whole cluster.",
    sourceTitle: "Google Search Central: control your snippets",
    sourceUrl: "https://developers.google.com/search/docs/appearance/snippet",
    insteadRules: ["content/meta-description-presence", "content/meta-uniqueness"],
  },
  {
    claim: "Title tags over 60 characters get penalised or rewritten",
    verdict: "False",
    reality:
      "Google's title-link page opens with the opposite of the folklore: while there is no limit on how long a title element can be, the title link is truncated in Search results as needed, typically to fit the device width. That is display-side cropping measured in pixels, not an indexing or ranking event, and no character count appears anywhere on the page. What the same page DOES document is why Google replaces a title link, and none of it is length: part of the title text missing (its own example is the literal \"| Site Name\"), boilerplate repeated across a subset of pages, a stale year on a page reused annually, a title that does not describe the page. pseolint checks the first two, which are mechanical; the last two need editorial judgement a crawler does not have, so we leave them to you rather than guess.",
    sourceTitle: "Google Search Central: influencing your title links",
    sourceUrl: "https://developers.google.com/search/docs/appearance/title-link",
    insteadRules: ["content/title-uniqueness"],
  },
  {
    claim: "og:description should be 70 characters",
    verdict: "Unsupported",
    reality:
      "No such number exists in any specification. Meta's sharing guide says a description is usually between 2 and 4 sentences; ogp.me asks for one to two sentences. Open Graph tags are not a ranking input at all, they shape the social and AI-summary card. What IS in the spec and widely missed: og:type and og:url are required properties.",
    sourceTitle: "ogp.me: the Open Graph protocol",
    sourceUrl: "https://ogp.me/",
    alsoSee: [
      {
        title: "Meta: a guide to sharing for webmasters",
        url: "https://developers.facebook.com/documentation/sharing/webmasters",
      },
    ],
    insteadRules: ["tech/og-completeness"],
  },
  {
    claim: "Search engines can only process 2 MB of total website size",
    verdict: "Misread",
    reality:
      "A real number attached to the wrong object. Googlebot's documented limit is 2 MB per fetched FILE, uncompressed: every HTML page, stylesheet and script gets its own budget, and PDFs get 64 MB. There is no total-site or total-page-weight crawl ceiling. A 21 MB page whose HTML is 112 kB has a Core Web Vitals problem, not a crawl-truncation one.",
    sourceTitle: "Google Search Central: Googlebot",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    insteadRules: ["tech/html-size", "tech/resource-weight", "tech/core-web-vitals"],
  },
  {
    claim: "Googlebot indexes the first 15 MB of your HTML",
    verdict: "Outdated",
    reality:
      "This one was true. The 15 MB figure lived in Google's documentation for years and most SEO tools still cite it. The February 2026 revision of the Googlebot page cut the documented per-file crawl limit to 2 MB. Folklore and fact swap places when the source document moves, which is why every rule here links to the living doc rather than a summary of it.",
    sourceTitle: "Google Search Central: Googlebot",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/googlebot",
    insteadRules: ["tech/html-size"],
  },
  {
    claim: "A missing meta keywords tag hurts your ranking",
    verdict: "False",
    reality:
      "Google's supported-tags page lists keywords as a tag it does not use, with no effect on indexing or ranking at all, and it has said so publicly since 2009. Any audit that still flags a missing keywords tag is dating itself.",
    sourceTitle: "Google Search Central: meta tags Google supports",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/special-tags",
  },
  {
    claim: "A wrong or missing html lang attribute is an SEO problem",
    verdict: "Misread",
    reality:
      "Google is explicit that it does not use code-level language information such as lang attributes, and detects language from visible content instead. The consequence cuts the other way: when your declared language and your actual content diverge, Google indexes by what it DETECTED, so the declared targeting silently fails. The attribute still matters for accessibility.",
    sourceTitle: "Google Search Central: managing multi-regional sites",
    sourceUrl:
      "https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites",
    insteadRules: ["tech/language-mismatch"],
  },
  {
    claim: "Sitemaps need priority and changefreq values",
    verdict: "False",
    reality:
      "Google documents that it ignores both. It does use lastmod, but only when the value is consistently and verifiably accurate. A sitemap that stamps every URL with the same generated timestamp teaches Google to distrust the one sitemap field that actually works.",
    sourceTitle: "Google Search Central: build and submit a sitemap",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap",
    insteadRules: ["tech/sitemap-hygiene"],
  },
  {
    claim: "Paginated archives need rel=next and rel=prev",
    verdict: "Obsolete",
    reality:
      "Google's pagination guidance is one sentence long and carries no date: in the past Google used rel=next and rel=prev to identify next-page and previous-page relationships, Google no longer uses these tags, although these links may still be used by other search engines. The 2019 announcement that made the rounds said support had already been dropped years earlier, so nobody outside Google knows when it actually stopped. Harmless to keep for whichever other engines read it; pointless to add for Google.",
    sourceTitle: "Google Search Central: pagination and incremental page loading",
    sourceUrl:
      "https://developers.google.com/search/docs/specialty/ecommerce/pagination-and-incremental-page-loading",
  },
  {
    claim: "Pages need 300 or more words to rank",
    verdict: "False",
    reality:
      "Google's helpful-content guidance answers this in its own words: are you writing to a particular word count because you heard Google has a preferred one? No, they do not. Word-count floors exist in SPAM detection at template scale, where a thousand 40-word pages differing by one city name is a doorway pattern, but that is a policy-risk signal rather than a per-page ranking factor.",
    sourceTitle: "Google Search Central: creating helpful content",
    sourceUrl: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    insteadRules: ["spam/thin-content", "content/unique-value"],
  },
  {
    claim: "Multiple meta description tags trigger a penalty",
    verdict: "Unsupported",
    reality:
      "Neither Google's documentation nor Lighthouse checks for it. Duplicated tags carrying different content are undefined behaviour worth tidying, but the place duplicates genuinely hurt is robots directives: Google applies the MOST RESTRICTIVE rule it finds across meta robots, meta googlebot and the X-Robots-Tag header, so one forgotten noindex in a conflicting pair silently wins.",
    sourceTitle: "Google Search Central: robots meta tag specifications",
    sourceUrl: "https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag",
    insteadRules: ["tech/meta-robots-conflict"],
  },
  {
    claim: "An hreflang set is invalid without x-default",
    verdict: "Unsupported",
    reality:
      "Google's wording is consider adding a fallback page and use the x-default value: a recommendation, not a requirement. What the same page does document as a hard constraint is the code itself: only ISO 639-1 languages and ISO 3166-1 Alpha 2 regions are supported, and it names es-419 outright as a code that is not. Read the failure precisely, because the popular summary overstates it: for a code reserved for something else, Google ignores THAT PART of the annotation, naming EU, UN and UK as examples. So en-UK is not discarded, it degrades to a bare en that now collides with whatever real en alternate the set already declares. Either way nothing is surfaced in Search Console.",
    sourceTitle: "Google Search Central: localized versions of your pages",
    sourceUrl: "https://developers.google.com/search/docs/specialty/international/localized-versions",
    insteadRules: ["tech/hreflang-validity", "tech/hreflang-consistency"],
  },
  {
    claim: "FAQPage JSON-LD earns you an FAQ rich result",
    verdict: "Obsolete",
    reality:
      "It did, for anyone, until September 2023, when Google narrowed the FAQ rich result to well-known authoritative government and health sites. It then stopped appearing at all: the changelog entry dated May 8, 2026 announced the feature would no longer appear in Google Search starting May 7, 2026, and on June 15, 2026 Google deleted the FAQPage documentation outright. There is no successor. QAPage still has a live rich result, but its own documentation restricts it to pages where users can submit answers, which a site-authored FAQ is not. Writing real question-and-answer content still pays, as extractable prose that an answer engine can lift whole; the markup no longer buys anything in Google Search.",
    sourceTitle: "Google Search Central: removing the FAQ rich result",
    sourceUrl: "https://developers.google.com/search/updates#removing-faq-rich-result",
    alsoSee: [
      {
        title: "Google Search Central: Q&A (QAPage) structured data",
        url: "https://developers.google.com/search/docs/appearance/structured-data/qapage",
      },
    ],
    insteadRules: ["aeo/faq-coverage", "aeo/answer-first"],
  },
  {
    claim: "CSS complexity hurts your ranking",
    verdict: "Unsupported",
    reality:
      "Rule counts, duplicated selectors, !important usage and vendor prefixes have no documented ranking role. They matter through exactly two documented mechanisms: a single file blowing past the per-file fetch limit, or rendering slow enough to degrade Core Web Vitals. Fix those two and selector count is a code-review topic rather than an SEO one.",
    sourceTitle: "Google Search Central: understanding page experience",
    sourceUrl: "https://developers.google.com/search/docs/appearance/page-experience",
    insteadRules: ["tech/html-size", "tech/core-web-vitals"],
  },
];
