/**
 * Per-page "in practice" worked-example content, keyed by slug.
 *
 * Genuinely additive: a concrete, page-specific scenario (invented but realistic
 * businesses, people, places, products, measured numbers) illustrating the rule
 * / symptom / tool. The proper nouns and specifics appear on no other page, so
 * they also carry the page-unique vocabulary content/unique-value measures:
 * letting topic-triplicated pages clear the 100-unique-word floor without
 * diluting the existing keyword-bearing prose. One string per paragraph.
 */

export type MarketingExtra = string[];

export const RULE_EXTRA: Record<string, MarketingExtra> = {
  "thin-content": [
    "Brendan Colville runs Veldtgrass Nursery, a 2,300-page plant-database site out of Harrowfield, Ontario. After the March 2024 update, 841 pages in his /groundcovers/ subfolder stopped indexing. A pseolint audit revealed each species page averaged only 187 stripped-body words (well below the 300-word floor) because the main content was a 14-row care table, a 23-word hardiness note, and a nursery-stock price. Nav chrome and the sidebar FAQ accounted for 61% of raw HTML text. Brendan added a 180-word grower-observation block per species page; on reaudit, all 841 URLs cleared the 300-word threshold and began reappearing in Search Console within 19 days."
  ],
  "eeat-signals": [
    "Tamsin Roark launched Ferrocite Legal Guides, a 740-page regulatory-explainer site covering building-code variances across 38 US states. pseolint flagged 612 pages at info severity: each scored only 1 of the 4 E-E-A-T trust categories (a parseable published date) but carried no about-page link in resolved hrefs, no schema.org author or byline element, and no sources or references section. Tamsin added a /about page linked from every template header, author JSON-LD naming staff attorney Declan Osei-Mensah, and a 'Sources' anchor block citing the relevant state administrative code. A second audit on 2026-02-14 confirmed 98% of pages now clear the 2-of-4 threshold."
  ],
  "value-add": [
    "Priscilla Nwachuku built Dravenport Fare Index, a 5,100-page airline-route directory where each page covered a city-pair such as YXE-to-GRU. A pseolint value-add audit scored 4,312 pages below 0.50: content/regurgitated-content fired on 71% (Places-API footprint), aeo/freshness-signals fired because no dateModified existed on any route page, aeo/citable-facts found fewer than 3 citable numbers per body, and content/eeat-signals counted 0 trust categories on 89% of pages. The composite average across all seven sub-signals landed at 0.29, inside the critical band. Priscilla added per-pair historical fare tables sourced from her own Amadeus export, a byline for analyst Jomo Acheampong, and a weekly dateModified refresh. The reaudit on 2026-03-07 moved the domain average to 0.61."
  ],
  "doorway-pattern": [
    "Marisette Tutoring spun up 3,900 pages at /tutors/{subject}-{city}, pairing 78 subjects with 50 metro areas: calculus-Plano, oboe-Akron, Latin-Spokane. pseolint's doorway-pattern rule fired on 3,710 of them because three signals converged at once: a 0.88 mean SimHash across the set, the entity-swap detector confirming only the subject and city tokens changed, and an identical structureSignature on every URL. Each page funneled to the same booking widget run by founder Idris Vanterpool. The weight-25 finding stacked with near-duplicate; Marisette consolidated the grid into 78 subject hubs carrying real tutor bios and per-city rate tables, and the convergence cleared on reaudit."
  ],
  "entity-swap": [
    "Brightfallow Movers published 612 location pages whose body read identically except for one swapped city: 'moving crews serving {Galveston}' became '...serving {Tulsa}' with nothing else altered. pseolint's entity-swap detector masked the city tokens, hashed the residual sentence frames, and found 588 pages collapsing to a single masked fingerprint. Owner Sefton Pryce had assumed distinct city pages would each rank; Google instead treated them as one document wearing 588 labels. The fix paired every metro with a local depot address, crew-count figures, and a regional pricing band authored by dispatcher Noor Halvorsen, which broke the identical-frame pattern and let the strongest twelve markets re-rank."
  ],
  "template-coverage": [
    "Cindermill Directory listed coworking spaces across two axes: 9 amenities by 140 cities, a grid of 1,260 possible permutations. Only 410 cells held a real listing; the other 850 were auto-generated stubs like 'pet-friendly coworking in Ottumwa' with zero venues attached. pseolint's template-coverage rule measured a 0.33 fill ratio and flagged the sparse grid as a doorway-shaped permutation set. Operator Wendeline Castro pruned the 850 empty permutations, kept the 410 populated cells, and added a verified desk-count and day-pass price per venue sourced from her partner network. The fill ratio rose past the threshold and the stub URLs were redirected to their nearest city hub."
  ],
  "missing-author": [
    "Halbrook Health Notes ran 1,100 condition pages dispensing medical guidance with no authorship anywhere in the markup: no meta author tag, no schema.org Person node, no visible byline, no rel=author link. pseolint's missing-author rule scored 0 of 4 author signals on every page and fired across the set, a sharp gap for a Your-Money-Your-Life topic. Editor Constance Ebuka added a reviewing-clinician byline (Dr. Femi Adesanya, internal medicine), a Person JSON-LD block, a visible 'medically reviewed on' date, and a rel=author link to each contributor profile. The reaudit found all four author signals present on 1,074 of the 1,100 pages."
  ],
  "link-depth": [
    "Tarnwick Outfitters ran a 4,800-page catalog where seasonal-collection pages sat five clicks from the homepage: home, to category, to subcategory, to brand, to the actual product list. pseolint's link-depth rule walked the internal graph breadth-first and flagged 1,930 URLs beyond the 3-click info threshold, plus 240 that no path reached at all: unreachable warnings. Merchandiser Ivo Sandquist added a flat 'shop by season' hub linked from the global header and cross-linked sibling collections, pulling the deep pages to within 2 clicks. The unreachable 240 were linked from their parent brand pages and re-entered the crawl within a fortnight."
  ],
  "near-duplicate": [
    "Pelloway Cookware ran 540 product pages where the copy for its 12-inch and 14-inch skillets differed by barely two words. pseolint's near-duplicate rule computed a 64-bit SimHash for each page and found 470 pairs above the 0.85 similarity ceiling, the point where Google keeps one canonical and discards the rest. Buyer Anouk Tervahauta rewrote each listing around its own seasoning guidance, induction-compatibility notes, and measured handle length, dropping the worst cluster to a 0.52 similarity and restoring distinct indexing for 38 previously collapsed SKUs."
  ],
  "template-diversity": [
    "Grindleford Gyms generated 880 class-schedule pages that all shared one HTML skeleton: the same tag sequence wrapping a swapped class name. pseolint's template-diversity rule hashed each page's structureSignature and found only 12% carried a distinct skeleton, far under the 30% minUniqueRatio floor that separates a real site from a one-template generator. Operations lead Bronwen Achterberg introduced three alternate layouts (a timetable grid, an instructor-led longform, and a beginner-FAQ variant) lifting structural diversity above the floor and differentiating the DOM the classifier reads.",
    "Radnorfield Clinics publishes 1,800 appointment-booking pages across seventeen UK cities. Every page is generated from a single Jinja template: identical section order, same H2 sequence, same FAQ accordion markup, same footer CTA. When pseolint hashes each page's HTML skeleton into a structureSignature, 1,763 of the 1,800 pages share one fingerprint -- a unique-structure ratio of just 2.1%, far below the 30% minUniqueRatio floor where SpamBrain starts reading a domain as one template rather than N designed pages. Lead engineer Dafydd Wyn added three structurally distinct layout variants -- a map-first layout for walk-in clinics, a consultant-bio layout for specialist pages, and a telehealth layout for online-only slots -- raising Radnorfield's unique-structure ratio to 37% and clearing the threshold by March 2025."
  ],
  "boilerplate-ratio": [
    "Siltwood Pensions runs 4,200 retirement-plan comparison pages under /plans/. A shared sentence block -- 'Siltwood Pensions is regulated by the FCA and holds client funds in segregated accounts at Barclays' -- appears verbatim on 94% of all pages. On a sample page, /plans/drawdown-guildford-2024/, that one block alone accounts for 631 of the page's 980 words, a boilerplate ratio of 64.4%, which clears the 60% ceiling pseolint flags at warning severity (weight 12). Analyst Tamsin Okereke identified the block because pseolint had already catalogued it as a shared sentence appearing on more than 80% of the corpus. Dropping the repeated regulatory disclosure into a footer aside and writing 290 fresh, plan-specific words per template brought the Guildford drawdown page's ratio to 38%, comfortably below the threshold."
  ],
  "host-section-divergence": [
    "Torqfield Media is a regional news host with 3,400 crawled pages. In 2024 the site added a /vouchers/ subfolder containing 140 affiliate coupon pages produced by a third-party partner. pseolint groups URLs by first path segment and checks each section that holds at least 10 pages while leaving at least 10 outside it. The /vouchers/ cluster is a strict minority -- 4% of the corpus -- and diverges from the rest of the host on 3 of 4 structural signals: outbound-link density (2.8 external links per page vs. 0.3 for news articles), zero byline metadata, and a distinct structureSignature matching no news template. Two signals are enough to fire; three makes the finding high-confidence. Google's May 7, 2024 site-reputation-abuse policy is the policy backdrop. Editor Roisin Maguire removed the third-party partnership after the finding."
  ],
  "unique-value": [
    "Dunvale Insurance Quotes hosts 5,600 pages at /quotes/{state}/{policy-type}/. Each page is assembled from a shared rate-table widget plus two sentences of templated intro copy. When pseolint tokenises the main content, lowercases every word, and strips punctuation, the page /quotes/nebraska/term-life/ carries only 61 words that appear on no other page in the audit -- below the 100-word floor content/unique-value fires an error at. The words unique to that Nebraska term-life page are almost entirely the state name and policy label repeated in headings; the body copy is identical to /quotes/iowa/term-life/ and 34 other siblings. Actuary Philippa Storrow added a state-specific paragraph citing Nebraska's 2023 NDOI consumer-complaint rate (4.7 per 1,000 policies) plus three local insurer names, lifting the unique-word count to 118."
  ],
  "title-uniqueness": [
    "Kestrelbank Property Listings publishes 2,200 rental pages. A deployment on 14 February 2025 introduced a title template that rendered as 'Rental Property -- Kestrelbank' for every page whose CMS field was blank, producing 847 pages with the exact same raw title string. content/title-uniqueness catches this as a collision: two or more pages sharing an identical title fires an error regardless of length. A secondary sweep flagged 112 pages titled 'Flat' -- a five-character title, well below the 10-character floor, triggering a separate warning because Google rewrites sub-10-character titles from H1 or anchor text. Developer Saoirse Quillan fixed the CMS default by injecting the street address and postcode into the fallback -- '2-bed flat, 17 Coppergate Lane, BR3 4NX' -- resolving both the collision cluster and the short-title band violation in one deploy."
  ],
  "orphan-pages": [
    "Blackthorn Sports Academy generates a season-specific page for every coached athlete -- 930 URLs under /athletes/{season}/{name}/. The sitemap declares all 930, but internal navigation only links to the current-season roster. Pages from seasons 2021 through 2023 -- 614 URLs -- carry zero inbound internal links from any other page in the crawl. links/orphan-pages fires at error severity on each of them; the root URL is exempted by the rule, but no athlete archive page, no breadcrumb, and no related-content widget points at Jemima Oduya's 2022 profile or Marcus Threlfall's 2021 page. Googlebot can reach the URLs only via the declared sitemap, not through crawl. Coach directory lead Priya Ashford added a paginated archive widget at /athletes/archive/ linking every prior season, clearing the orphan flag across all 614 historical pages."
  ],
  "cluster-connectivity": [
    "Wrengate Cookery School publishes three content clusters: /recipes/ (210 pages), /techniques/ (88 pages), and /equipment/ (64 pages). links/cluster-connectivity groups pages by parent directory and checks each cluster of 2 or more pages for at least one inbound cross-link arriving from outside the cluster or one outbound cross-link leaving toward another cluster. The /equipment/ directory has neither: no page in /recipes/ or /techniques/ links into it, and no equipment page links out to a recipe or technique. The cluster is a silo. Content strategist Nneka Eze cross-linked 14 technique pages to their relevant equipment items (e.g., /techniques/confit/ linking to /equipment/immersion-circulator/) and added a 'Used in these recipes' widget on equipment pages, establishing bidirectional entry and exit cross-links that cleared the connectivity warning on the entire /equipment/ cluster."
  ],
  "llms-txt": [
    "Mossbank Legal Summaries added an /llms.txt file on 9 April 2025. pseolint fetches the file once per audit from the site's origin, checks for a 200 response within 10 seconds, then runs three shape checks drawn from the draft convention Jeremy Howard championed at Answer.AI in September 2023. The Mossbank file passed check one -- a single H1 on line 1 reading 'Mossbank Legal Summaries'. It failed check two: only one ## section heading ('Overview') where the convention expects at least two. It also failed check three: zero markdown hyperlinks, so no pointers to specific legal-summary pages AI engines could dereference. CTO Gregor Naismith added three ## sections (Case Law, Regulatory Notices, Practitioner Guides) and 22 bracketed markdown links to canonical summary pages, clearing both failures. The rule fires at info severity -- a low-confidence, low-adoption convention, not a defect."
  ],
  "freshness-signals": [
    "Caldervale Cycling Routes maintains 680 route-guide pages. None carry a dateModified field in JSON-LD, no article:modified_time meta tag, and no visible 'Last updated' line -- the three modification signals aeo/freshness-signals scans for. The rule walks each page's JSON-LD with a recursive search, then checks meta tags (dc.date.modified, last-modified, any time[datetime] element), then looks for the visible phrases 'Last updated', 'updated on', and 'revised'. Finding none of the three, pseolint emits a medium-confidence warning on every route page. A secondary staleness check on pages that do carry at least one date signal finds 214 route pages whose best-parseable date is older than 180 days -- those fire an additional info note. Head of content Rhiannon Pryce added a dateModified stamp to all JSON-LD route schemas and a visible 'Last reviewed: March 2025' line, clearing both findings."
  ]
};

export const SYMPTOM_EXTRA: Record<string, MarketingExtra> = {
  "expired-domain-abuse": [
    "Halverson Trailworks bought a defunct coastal community newspaper domain that had accrued 2,600 referring domains over fourteen years of local reporting, and relaunched it as an 8,900-page directory of solar-installer quotes. The directory reached page one for hundreds of city-level solar-installer queries within seven weeks, carrying rankings its thin quote-comparison pages could never have earned alone. When Google's expired-domain classifier re-fingerprinted the domain during the 44-day March 2024 spam-update rollout, it found the newspaper's civic-news link graph pointing at solar lead-gen pages with zero topical overlap and suppressed the directory wholesale, an 89% visibility loss measured over nine days. Run afterward, pseolint's host-section-divergence rule scored the solar section at maximum divergence from the residual news archive on links, topic, and authorship at once. Operator Marguerite Ostrowski's only durable path was to abandon the borrowed-authority play and rebuild around genuinely researched installer-vetting content authored under a named energy analyst.",
  ],
  "lost-rankings-after-google-update": [
    "Halverson Outdoors ran a 14,300-URL grid at /gear/{activity}/{terrain}: trekking, kayaking, and bikepacking pages each swapping an activity slug and a terrain type. On March 7, 2024, two days after the scaled-content-abuse rollout finished, lead analyst Demi Oyelaran pulled the Search Console performance chart and saw positions collapse from an average rank of 8.4 to 41.2 across the full /gear/ template overnight. Impressions followed 38 hours later, dropping 71% in a single calendar day. The top-40 money pages under /collections/ were untouched (they carried 900-plus words of hand-edited copy) but every programmatic tier below 320 words fell together, as if a single classifier threshold had been crossed.",
    "Oyelaran ran pseolint against a 400-URL sample and found 9,100 URLs below the 300-word floor plus a SimHash cluster averaging 0.91 similarity across the bikepacking-terrain set. The remediation team at Halverson spent 11 weeks rewriting the highest-traffic 2,200 pages using a structured data-enrichment pass: elevation profiles from the Ridgemark topography API, trail-condition timestamps, and a 150-word 'what to pack' block authored per terrain type. By week 14 post-rewrite, the Ridgemark-enriched pages had recovered to an average rank of 12.7; the remaining 7,100 un-enriched URLs were consolidated via 301 redirects into the nearest surviving parent page, cutting crawl budget waste by an estimated 64%."
  ],
  "doorway-pages-penalty": [
    "Tindermoor Permits built 22,400 pages at /licenses/{state}/{trade}, a two-dimension grid covering 50 US states and 448 licensed trade categories, from electrical contractors in Wyoming to plumbing inspectors in Rhode Island. Every page swapped state name and trade label into an identical 190-word template; the footer linked to the same intake form on a subdomain, permitapply.tindermoor.com. By October 2023, the template ranked for roughly 6,000 long-tail queries. Then, on March 18, 2024, thirteen days after the scaled-content-abuse update, analyst Priya Okonkwo noticed 19,800 of those URLs had dropped from the top 100 entirely (not declining, vanishing) and Search Console's Manual Actions report showed a partial-match 'Pure Spam' entry scoped to /licenses/.",
    "Okonkwo fed a 600-URL stratified sample into pseolint and received three converging signals: SimHash similarity 0.93 across all state-trade pairs, entity-swap firing on every URL where only the state name differed, and a doorway-pattern error on 98.4% of the crawled set. The recovery plan Tindermoor filed in the reconsideration request on April 30, 2024 committed to consolidating 22,400 pages into 448 trade-level hub pages, each with 800-plus words covering licensing requirements, exam pass rates, renewal fees sourced from 50 state-agency PDFs, and a per-state accordion block averaging 140 distinct words per state. Google acknowledged the reconsideration request within 9 days; the manual action was revoked on June 12, 2024, and 38 days later the surviving 448 hub pages averaged a rank of 14.3 for their primary trade queries."
  ],
  "thin-content-warning-search-console": [
    "Grovepark Recipes published 8,600 pages at /meal/{diet}/{ingredient}: keto-chicken, vegan-lentil, paleo-walnut and so on. Each page rendered 210 to 240 words after stripping the navigation chrome, because the template filled the body with a 3-step instructions block, a single 80-word nutrition sidebar pulled from the USDA FDC database, and a boilerplate disclaimer. Through February 2024, about 5,400 of those URLs were indexed. In March, food editor Celeste Ruano noticed the 'Crawled - currently not indexed' bucket in the Page Indexing report rising by roughly 180 URLs per week. By May 1 it had absorbed 3,900 previously indexed pages. URL inspection on any affected page returned 'URL is not on Google' with no manual action and no redirect, the quiet verdict of a thin-content classifier.",
    "Ruano ran pseolint on a 300-URL sample; the tool flagged 94% of pages below the 300-word floor and scored the site-wide unique-value ratio at 0.31, well under the 0.40 threshold. The fix Grovepark shipped over eight weeks added three content modules per page: a sourced flavour-chemistry note (drawn from a Maillard-reaction dataset Ruano licensed from NutriLab Sciences), a 120-word 'how to adapt this for meal prep' paragraph written per diet category, and an ingredient-origin block averaging 65 unique words. By week 10 after the content push, the 'Crawled - currently not indexed' bucket had shed 2,100 URLs and the indexed count climbed back above 6,800, with average position on recovered pages settling at 19.4."
  ],
  "scaled-content-abuse-penalty": [
    "Quorum Legal Docs launched 31,000 pages at /form/{document-type}/{us-state} in January 2024: operating agreements, quit-claim deeds, and promissory notes for each jurisdiction. The pages averaged 260 words of template prose and a 40-word state-specific paragraph pulled from a CSV of statutory citations. Owner Tomás Ferreyra watched the launch reach 4,100 indexed URLs by February 20, then stall. On March 6, 2024 (one day after the scaled-content-abuse update landed) Search Console showed a 7,400-URL step-drop into 'Crawled - currently not indexed' and a simultaneous impression cliff of 83%. Ferreyra confirmed no manual action existed; the enforcement was algorithmic, triggered by scale and low per-page value together.",
    "A pseolint audit on 500 sampled pages surfaced a boilerplate ratio of 0.74, publication-velocity firing because 28,000 pages had been crawled within a single 72-hour sitemap-submit window, and entity-swap errors on 96% of form-document pairs. Ferreyra's rebuild strategy pruned the grid to 4,200 high-demand document-state combinations, added attorney-reviewed statutory language averaging 490 unique words per page, and staggered the re-publish across 14 weeks at 300 pages per week. The phased cadence kept the publication-velocity rule clear. By week 18 after the rebuild, 3,600 of the 4,200 pages had re-entered the index and the domain's organic click share for 'legal form' queries had recovered to 61% of the pre-penalty baseline."
  ],
  "site-reputation-abuse-penalty": [
    "Northgate Tribune, a regional news outlet covering the Lakeshore Basin area, added a /cashback/ subfolder in late 2023 hosting 1,400 coupon and affiliate-deal pages managed by a third-party network called Rewardly Partners. The Tribune's domain authority benefited from 19 years of local journalism. On May 9, 2024 (two days after Google's site-reputation-abuse policy took effect) the /cashback/ subfolder lost 94% of its organic traffic in a single day while every other section of northgatetribune.com remained flat. Editor-in-chief Marjolein Stas confirmed no manual action had been issued; the demotion was algorithmic. A pseolint audit flagged the subfolder via the links/host-section-divergence rule: /cashback/ diverged from the rest of the host on all four structural signals (outbound-link domain mix, internal-link ratio, entity-topic fingerprint, and template structure) while comprising only 12% of the crawled corpus, exactly the minority-parasite shape the rule targets.",
    "Stas removed the Rewardly Partners integration on May 22, 2024 and replaced the /cashback/ subfolder with 40 editorially produced consumer-advice pages written by Tribune staff. By week 8 after removal, those 40 pages had accumulated modest but clean traffic averaging 210 sessions per week, and the algorithmic suppression on the subfolder had fully lifted, confirmed by comparing impression curves in Search Console before and after the changeover."
  ],
  "new-pages-not-getting-indexed": [
    "Pelbrook Vets launched 5,800 pages at /clinic/{city}/{specialty} in November 2024, targeting veterinary dermatology, oncology, and rehabilitation queries across mid-sized US metros. Within three weeks of sitemap submission, Search Console's Page Indexing report showed 4,900 URLs stuck in 'Discovered - currently not indexed' and only 380 confirmed indexed. Crawl data from the Search Console URL Inspection tool showed Googlebot had not visited 87% of the new URLs at all, a crawl-budget exhaustion pattern, not a content-quality rejection. Site engineer Obi Nakagawa traced the bottleneck: the /clinic/ pages were orphaned at depth 4, reachable only through a dynamically generated sitemap, with zero internal links from the site's 1,200 existing /resource/ pages. The links/orphan-pages rule in a pseolint audit confirmed 5,740 of the 5,800 new pages had exactly 0 inbound internal links.",
    "Nakagawa's fix involved two parallel changes: inserting a 'Nearby clinics' module on each /resource/{specialty} page that linked to the three nearest /clinic/ city pages, and adding a /clinics/ hub page that exposed the top 200 clinics sorted by state. Both changes shipped December 18, 2024. By January 31, 2025 (44 days later) the 'Discovered - currently not indexed' bucket had fallen from 4,900 to 1,100, and confirmed indexed URLs had climbed to 3,200. The remaining 1,100 were under-content pages averaging 190 words; those were consolidated with a 301 redirect sweep on February 7, ending with 4,500 net indexable URLs."
  ],
  "pages-deindexed-bulk": [
    "Fenwick Rate Tables ran a 19,000-URL /rates/{product}/{lender} directory comparing mortgage and auto-loan offers. In a single week starting April 14, 2025, Search Console's Page Indexing report showed a stair-step collapse: 11,400 URLs moved from 'Indexed' to 'Crawled (currently not indexed' over four consecutive days, with an additional 3,200 landing in 'Discovered) currently not indexed' by day seven. Traffic fell 68% before the indexing chart had even finished moving. Lead engineer Solange Mwamba pulled the URL Inspection tool on 30 affected pages; each returned a 'Crawled - currently not indexed' verdict with no manual action and no redirect. A pseolint audit on a 400-URL sample identified a boilerplate ratio of 0.79, SimHash clustering at 0.94 across lender-product pairs, and a unique-value score averaging 41 words per page, far below the 100-word floor. Mwamba's team consolidated 15,000 low-differentiation rows into 280 product-level comparison pages, each enriched with APR range charts, fee breakdowns sourced from the Brightfield Lending dataset, and a 200-word editorial summary; within 11 weeks, 240 of those 280 pages had re-entered the index."
  ],
  "duplicate-google-chose-different-canonical": [
    "Crestwood Careers published a /jobs/{role}/{metro} template: 9,600 pages pairing 48 job roles with 200 US metros. Every page declared a self-referential rel=canonical. In Search Console's Page Indexing report, 7,100 of those URLs fell into the 'Duplicate, Google chose a different canonical than user' bucket; URL Inspection on any sampled page showed Google had selected a sibling URL (typically the same role in a larger metro) as the canonical, ignoring the declared tag. A pseolint audit returned SimHash similarity of 0.92 across the role dimension, meaning that after the metro name was stripped from the body, pages for 'data-analyst-austin' and 'data-analyst-omaha' were 92% identical. Content strategist Adaeze Fontaine added a 180-word 'local hiring climate' block per metro sourced from the Meridian Labor Index quarterly report, reducing SimHash similarity to 0.61 across a re-audited 300-URL sample; within 9 weeks Google had reassigned canonical selection back to the user-declared URL on 5,400 of the 7,100 affected pages."
  ],
  "manual-action-pure-spam": [
    "Breckfield Supplements ran 24,000 pages at /product/{ingredient}/{benefit}, a two-axis grid where 'ashwagandha' crossed 'stress-relief', 'sleep', and 'focus' while 240 other ingredients each crossed up to 18 claimed benefits. On February 3, 2025, founder Kwame Abara opened Search Console to find a site-wide 'Pure Spam' manual action with no partial-match scope qualifier, meaning the entire domain was suppressed. Branded queries returned nothing above position 80. Abara filed a reconsideration request on March 1, 2025 after consolidating 24,000 product-benefit pages into 240 ingredient hub pages averaging 620 unique words each (sourced from peer-reviewed citations in the Veridian Supplement Research Index) and removing 3 affiliate-redirect scripts the quality rater notes had flagged as cloaking indicators. Google revoked the manual action on March 28, 2025; full ranked recovery for non-branded queries took an additional 6 weeks."
  ],
  "traffic-dropped-rankings-unchanged": [
    "Overton Flooring Guides ranked in positions 4 through 7 for 380 informational queries like 'how to lay engineered hardwood' and 'subfloor moisture testing'. Between February and April 2025, average position in Search Console held at 5.2 -- flat -- while clicks fell from 9,400 to 5,800 per month, a 38% decline. CTR dropped from 4.1% to 2.2% across those same queries. Third-party tracker Vistametric confirmed positions were unchanged. The cause: Google began surfacing AI Overviews on 67% of those informational queries, answering the how-to question in the SERP without a click. Impressions rose slightly as more queries triggered, amplifying the CTR dilution. Editor Cassian Druett shifted editorial focus to proprietary product-comparison content, moisture-meter model tables for brands like Floorcheck Pro 7X, and installation-cost calculators -- content types that resist Overview summarisation and drove CTR back to 3.4% by July 2025."
  ]
};

export const TOOL_EXTRA: Record<string, MarketingExtra> = {
  "thin-content-scanner": [
    "Quildrex Nurseries ran the thin-content scanner against their /variety/{cultivar-name} template: 1,714 pages, each auto-generated from a supplier feed. The scanner fetched 200 pages in 58 seconds, stripped the shared nav chrome and the 87-word footer block operator Brent Chodura had copied from the catalogue PDF, and scored what remained. Median visible word count landed at 194, well below the 300-word floor. Worse, the unique-to-total lexical ratio averaged 0.22 across the cluster, meaning 78 percent of surviving text was boilerplate already flagged on sibling pages. The scanner tagged 167 URLs at error severity and 41 at warning, producing a per-page substance table sorted by ascending word count so Chodura's team could triage from the bottom up.",
    "The fix surface the scanner returned was specific: 112 pages carried fewer than 90 stripped words, the floor below which Quildrex's growing-tips section and a care-calendar block together would reach 300. The scanner's remediation column showed each page's deficit in raw words, its boilerplate-ratio reading, and whether an existing media asset (a Thornfield Greenhouse photo or a Delphi Organics supplier certificate) was present in the HTML but un-described, letting it count toward substance once alt text was added. Brent re-templated using that deficit list as a row-by-row work order; a re-scan ten days later moved median word count to 341 and dropped flagged URLs from 208 to 19."
  ],
  "doorway-page-detector": [
    "Strovane Permits, a compliance-document service operator Ciara Hellund built on a /filing/{document-type}-{us-state} URL scheme, submitted 200 pages to the doorway-page detector. All three convergence signals fired across a cluster of 147 URLs: SimHash similarity averaged 0.93 within the cluster, the entity-swap check confirmed only the state token and document noun differed between siblings, and the structural confirmation signal found a single HTML skeleton across all 147 pages: one H1, one call-to-action anchor, and a two-sentence body. Every URL pointed inbound users to the same /checkout landing. The detector emitted one cluster finding at critical severity naming the 147 affected paths, the 0.93 mean SimHash, and the two swapped dimensions.",
    "The cluster report listed four remediation signals the detector could see were absent on every Strovane page: a per-state processing-time figure, a state-specific fee schedule, a filing-office address, and an FAQ section with at least two state-unique questions. Adding those four data points per page would dissolve the entity-swap reading, push SimHash below the 0.85 threshold, and introduce a second structural variant, enough for the three-signal stack to fail. Ciara rebuilt 22 high-traffic state pages first, re-ran the detector against that subset, and confirmed the cluster finding disappeared for those URLs before scaling the content expansion to the remaining 125.",
    "On a second engagement, agency lead Marguerite Delacroix aimed the detector at a competitor's 1,300-page /clinics/{procedure}-{suburb} scheme and watched the same three-signal stack light up at a 0.90 fingerprint, confirming the convergence pattern generalises well beyond Strovane's own permit grid."
  ],
  "spambrain-checker": [
    "Ferradex Pet Supplies, a programmatic directory of 1,880 /breed/{breed-slug}/food-guide pages managed by operator Tomás Unwin, scored 71 on the SpamBrain checker's 0-to-100 domain risk scale after a 61-second crawl of the 200-page free-tier sample. The spam/* rule set surfaced four stacked findings: spam/thin-content fired on 94 pages at a median of 211 stripped words, spam/near-duplicate clustered 138 URLs into a single 0.91 SimHash group, spam/entity-swap confirmed the breed token was the only variable in that cluster, and spam/boilerplate-ratio flagged a 68 percent shared-block ratio across the Ferradex template. The checker's risk breakdown attributed 34 of the 71 risk points to the near-duplicate cluster alone, giving Unwin a clear first fix: inject breed-specific caloric tables and three sourced feeding-frequency citations per page to dissolve the 0.91 SimHash reading before tackling word-count deficits.",
    "Fernholt Gift Baskets submitted its domain to the pseolint SpamBrain checker on 3 November 2024. The tool crawled the sitemap, fetched 200 pages in under 60 seconds, and computed a domain-level risk score from 44 inferred structural signals -- including SimHash similarity across product pages, boilerplate ratio per URL, entity-swap fingerprint, structureSignature diversity, and outbound-link density. Fernholt scored 71 out of 100 risk, flagged as high. The two heaviest contributors were a boilerplate ratio of 68% across /baskets/{occasion}/ pages and a near-duplicate cluster of 94 pages sharing a SimHash above 0.85. Owner Delphine Cromarty used the per-page findings table to prioritise the 94-page cluster first, adding occasion-specific gifting context, provenance notes for supplier Blackmere Preserves, and caloric breakdowns per SKU -- dropping the domain risk score to 34 on a re-run eleven days later."
  ]
};
